class Pro {
  String name;
  String total;
  String image;
  String publisher;
  String kurdi;
  String video;
  String wana;
  String content;
  Pro(
      {required this.name,
      required this.total,
      required this.image,
      required this.publisher,
      required this.kurdi,
      required this.video,
      required this.wana,
      required this.content});
}

final pro = [
  Pro(
      name: "بەزمانی کوردی",
      total: 'Introduction Flutter Corse Kurdish-پێشەکی کۆرسی فلاوتەر کوردیش ',
      publisher: 'Taco Group',
      image: 'images/flutter.png',
      kurdi: 'Introduction Flutter Corse Kurdish-پێشەکی کۆرسی فلاوتەر کوردیش ',
      video: 'PP9CDeN07QI',
      wana: "1",
  content:
        "زمانی جاڤا، هەرچەندە گریمانەییە، بەڵام وەک زمانێکی مۆدێرن و ئاست بەرزی بەرنامەسازی پێشبینی دەکرێت کە بۆ سادەیی و کارایی و گونجانی نێوان پلاتفۆرمەکان داڕێژراوە. سوودە سەرەکییەکانی بریتین لە:\n"
        "1. سادەیی و خوێندنەوە: ڕستەسازییەکی ئاسان بۆ خوێندنەوە کە هەڵەکان کەمدەکاتەوە و ئۆنبۆردکردن خێراتر دەکات.\n"
        "2. کتێبخانەی ستانداردی بەهێز: کاراییە گشتگیرەکانی ناوەوە بۆ کەمکردنەوەی وابەستەیی بە کتێبخانە دەرەکییەکان.\n"
        "3. گونجانی نێوان پلاتفۆرمەکان: کارکردنی بێ کێشە لە سەرانسەری سیستەمی کارپێکردنی جیاوازدا.\n"
        "4. کارایی بەرزکراوە: باشتر کراوە بۆ بەڕێوەبردنی کارامەی بیرگە و جێبەجێکردنی خێرا.\n"
        "5. تایپکردنی بەهێز لەگەڵ نەرمی: تایپکردنی بەهێز لەگەڵ دەرئەنجامدانی جۆر و تایپکردنی داینامیکی تێکەڵ دەکات.\n"
        "6. پشتگیری هاوکاتی و هاوتەریبی: تایبەتمەندییە بنیات نراوەکان بۆ بەرنامە فرە ڕەگەکانی قەبارەدار.\n"
        "7. ئامرازەکانی پەرەپێدانی مۆدێرن: پشتگیری دەکرێت لەلایەن IDE و دیباگەر و ئامرازەکانی تری بەرزکردنەوەی بەرهەمهێنان.\n"
        "8. سەلامەتی و ئاسایش: جەخت لەسەر سەلامەتی بیرگە، سەلامەتی پووچ و پاراستن لە لاوازییەکان دەکاتەوە.\n"
        "9. کۆمەڵگە و ئیکۆسیستەم: کۆمەڵگەی گەشەپێدەری زیندوو کە کتێبخانە و چوارچێوەی بەرفراوانی هەیە.\n"
        "10. کارکردنی یەکتر: یەکگرتنی بێ کێشە لەگەڵ زمان و سیستەمەکانی تر.\n",
  ),
  Pro(
      name: "بەزمانی کوردی",
      total: 'what is flutter ?-فلاوتەر چییە ',
      publisher: 'Taco Group',
      image: 'images/flutter.png',
      kurdi: 'what is flutter ?-فلاوتەر چییە ',
      video: 'JdH41d4QQqc',
      wana: "2",
      content: ""),
  Pro(
      name: "بەزمانی کوردی",
      total:
          'Download and instal Flutter on Windows-داگرتن و دابەزاندنی فلاوتەر لەویندۆز',
      publisher: 'Taco Group',
      image: 'images/flutter.png',
      kurdi:
          'Download and instal Flutter on Windows-داگرتن و دابەزاندنی فلاوتەر لەویندۆز',
      video: 'PcHPIkp8EE',
      wana: "3",
      content: ""),
  Pro(
      name: "بەزمانی کوردی",
      total: 'Instal Flutter In Mac OS - دەوڵۆند کردن فلاوتەر لە ماک ئۆئیس',
      publisher: 'Taco Group',
      image: 'images/flutter.png',
      kurdi: 'Instal Flutter In Mac OS - دەوڵۆند کردن فلاوتەر لە ماک ئۆئیس',
      video: 'fHpqE50Z0Dg',
      wana: "4",
      content: ""),
  Pro(
      name: "بەزمانی کوردی",
      total: 'Instal Flutter On Linux-دامەزراندنی فلاوتەر لەسەر لینوکس',
      publisher: 'Taco Group',
      image: 'images/flutter.png',
      kurdi: 'Instal Flutter On Linux-دامەزراندنی فلاوتەر لەسەر لینوکس',
      video: '6ovHTRP5OOQ',
      wana: "5",
      content: ""),
  Pro(
      name: "بەزمانی کوردی",
      total:
          'Instal and Android Studio set up On All Platform -دابەزاندی و ستۆدیۆی ئەندرۆید لەسەر هەموو پلاتفۆرمێک دانراوە',
      publisher: 'Taco Group',
      image: 'images/flutter.png',
      kurdi:
          'Instal and Android Studio set up On All Platform -دابەزاندی و ستۆدیۆی ئەندرۆید لەسەر هەموو پلاتفۆرمێک دانراوە',
      video: 'kZObqpme-sE',
      wana: "6",
      content: ""),
  Pro(
      name: "بەزمانی کوردی",
      total:
          "Instal and Visual Studio Code setup On All Platforms -ڕێکخستنی کۆدی دامەزراندن و ڤیژوئال ستۆدیۆ لەسەر هەموو پلاتفۆرمەکان ",
      publisher: 'Taco Group',
      image: 'images/flutter.png',
      kurdi:
          "Instal and Visual Studio Code setup On All Platforms -ڕێکخستنی کۆدی دامەزراندن و ڤیژوئال ستۆدیۆ لەسەر هەموو پلاتفۆرمەکان ",
      video: 'CqPrmDh2vr0',
      wana: "7",
      content: ""),
  Pro(
      name: "بەزمانی کوردی",
      total:
          "Create Emulator in Android Studio  - دروستکردنی لیتەر لە ئەندرۆید ستۆدیۆ",
      publisher: 'Taco Group',
      image: 'images/flutter.png',
      kurdi:
          "Create Emulator in Android Studio  - دروستکردنی لیتەر لە ئەندرۆید ستۆدیۆ",
      video: 'XH1xQVjxbig',
      wana: "8",
      content: ""),
  Pro(
      name: "بەزمانی کوردی",
      total: "Instal iOS Simulator -  دابەزاندی سیمۆلیتەری ئای ئۆ ئێس",
      publisher: 'Taco Group',
      image: 'images/flutter.png',
      kurdi: "Instal iOS Simulator -  دابەزاندی سیمۆلیتەری ئای ئۆ ئێس",
      video: 'FdwjoZiuw9c',
      wana: "9",
      content: ""),
  Pro(
      name: "بەزمانی کوردی",
      total: "Flutter Widget - فلۆتەر ویجت ",
      publisher: 'Taco Group',
      image: 'images/flutter.png',
      kurdi: "Flutter Widget - فلۆتەر ویجت ",
      video: 'encsBymuueM',
      wana: "10",
      content: ""),
  Pro(
      name: "بەزمانی کوردی",
      total: "Flutter first application - فلۆتەر یەکەم بەکارهێنان ",
      publisher: 'Taco Group',
      image: 'images/flutter.png',
      kurdi: "Flutter first application - فلۆتەر یەکەم بەکارهێنان ",
      video: 'ONKtLrILiTU',
      wana: "11",
      content: ""),
  Pro(
      name: "بەزمانی کوردی",
      total: "Flutter Material widget - فلاوتەر مادەی ویجتەکەی ",
      publisher: 'Taco Group',
      image: 'images/flutter.png',
      kurdi: "Flutter Material widget - فلاوتەر مادەی ویجتەکەی ",
      video: 'G9Ety81AT-E',
      wana: "12",
      content: ""),
  Pro(
      name: "بەزمانی کوردی",
      total: "Flutter Stateful Widget - فلۆتەر ستاتفول ",
      publisher: 'Taco Group',
      image: 'images/flutter.png',
      kurdi: "Flutter Stateful Widget - فلۆتەر ستاتفول ",
      video: 'ByxCAyne3h0',
      wana: "13",
      content: ""),
  Pro(
      name: "بەزمانی کوردی",
      total: "Flutter Stateless Widget - ویجتەکەی فلۆتەر ستێتلێس",
      publisher: 'Taco Group',
      image: 'images/flutter.png',
      kurdi: "Flutter Stateless Widget - ویجتەکەی فلۆتەر ستێتلێس",
      video: '1SWLI7bMYAc',
      wana: "14",
      content: ""),
  Pro(
      name: "بەزمانی کوردی",
      total: "Flutter Material App - ئەپی مادەی فلۆتەر",
      publisher: 'Taco Group',
      image: 'images/flutter.png',
      kurdi: "Flutter Material App - ئەپی مادەی فلۆتەر",
      video: 'ZxxV3P7K2Iw',
      wana: "15",
      content: ""),
  Pro(
      name: "بەزمانی کوردی",
      total: "16_Flutter Scaffold -فلۆتەر سکافۆڵد",
      publisher: 'Taco Group',
      image: 'images/flutter.png',
      kurdi: "Flutter Scaffold -فلۆتەر سکافۆڵد",
      video: 'L8XRuNBlSgc',
      wana: "16",
      content: ""),
  Pro(
      name: "بەزمانی کوردی",
      total: "Flutter AppBar by TACO Group-فلۆتەر ئەپبار ",
      publisher: 'Taco Group',
      image: 'images/flutter.png',
      kurdi: "Flutter AppBar by TACO Group-فلۆتەر ئەپبار ",
      video: 'FL9AnzRZYjA',
      wana: "17",
      content: ""),
  Pro(
      name: "بەزمانی کوردی",
      total: "Flutter Drawer part 1 - فلاوتەر دراوەر بەشی یەک",
      publisher: 'Taco Group',
      image: 'images/flutter.png',
      kurdi: "Flutter Drawer part 1 - فلاوتەر دراوەر بەشی یەک",
      video: 'qSNggubfOGo',
      wana: "18",
      content: ""),
  Pro(
      name: "بەزمانی کوردی",
      total: "Flutter Drawer part 1 - فلاوتەر دراوەر بەشی یەک",
      publisher: 'Taco Group',
      image: 'images/flutter.png',
      kurdi: "Flutter Drawer part 2 - فلاوتەر دراوەر بەشی دوو",
      video: 'lzJtQcu56nE',
      wana: "19",
      content: ""),
  Pro(
      name: "بەزمانی کوردی",
      total:
          "Flutter Create new file or folder -فلاوتەر دروستکردنی فایل یان فۆڵدەرێکی نوێ",
      publisher: 'Taco Group',
      image: 'images/flutter.png',
      kurdi:
          "Flutter Create new file or folder -فلاوتەر دروستکردنی فایل یان فۆڵدەرێکی نوێ",
      video: '6Jmdkx85rLs',
      wana: "20",
      content: ""),
  Pro(
      name: "بەزمانی کوردی",
      total: "Flutter Center Widget -ویجتەکەی سەنتەری فلۆتەر",
      publisher: 'Taco Group',
      image: 'images/flutter.png',
      kurdi: "Flutter Center Widget -ویجتەکەی سەنتەری فلۆتەر",
      video: 'nnyriskfPX8',
      wana: "21",
      content: ""),
  Pro(
      name: "بەزمانی کوردی",
      total: "Flutter Text Widget - ویجتێکی دەقی فلۆتەر ",
      publisher: 'Taco Group',
      image: 'images/flutter.png',
      kurdi: "Flutter Text Widget - ویجتێکی دەقی فلۆتەر ",
      video: 'c-pYUe8rmm4',
      wana: "22",
      content: ""),
  Pro(
      name: "بەزمانی کوردی",
      total: "Flutter TextStyle Widget  -ویجتێکی شێوازی دەقی فلۆتەر",
      publisher: 'Taco Group',
      image: 'images/flutter.png',
      kurdi: "Flutter TextStyle Widget  -ویجتێکی شێوازی دەقی فلۆتەر",
      video: 'E6j2IdxE-DM',
      wana: "23",
      content: ""),
  Pro(
      name: "بەزمانی کوردی",
      total: "Flutter Container Widget-ویجتێکی کۆنتێنەری فلۆتەر",
      publisher: 'Taco Group',
      image: 'images/flutter.png',
      kurdi: "Flutter Container Widget-ویجتێکی کۆنتێنەری فلۆتەر",
      video: 'KOPpFVn0Nlc',
      wana: "24",
      content: ""),
  Pro(
      name: "بەزمانی کوردی",
      total: "Flutter boxDecoration Widget -ویجت بۆ ڕازاندنەوەی سندوقی فلۆتەر ",
      publisher: 'Taco Group',
      image: 'images/flutter.png',
      kurdi: "Flutter boxDecoration Widget -ویجت بۆ ڕازاندنەوەی سندوقی فلۆتەر ",
      video: 'CACqJ2ofmCo',
      wana: "25",
      content: ""),
  Pro(
      name: "بەزمانی کوردی",
      total:
          "Flutter Image with boxDecoration - وێنەی فلۆتەر لەگەڵ بۆکس دیکۆرات",
      publisher: 'Taco Group',
      image: 'images/flutter.png',
      kurdi:
          "Flutter Image with boxDecoration - وێنەی فلۆتەر لەگەڵ بۆکس دیکۆرات",
      video: 'PWaTTue3oOU',
      wana: "26",
      content: ""),
  Pro(
      name: "بەزمانی کوردی",
      total:
          "Flutter border with boxDecoration -سنووری فلۆتەر لەگەڵ بۆکس دیکۆرات ",
      publisher: 'Taco Group',
      image: 'images/flutter.png',
      kurdi:
          "Flutter border with boxDecoration -سنووری فلۆتەر لەگەڵ بۆکس دیکۆرات ",
      video: 'v3TIT7zVsXE',
      wana: "27",
      content: ""),
  Pro(
      name: "بەزمانی کوردی",
      total: "Flutter Column Widget  -ویجتەکەی ستوونی فلۆتەر",
      publisher: 'Taco Group',
      image: 'images/flutter.png',
      kurdi: "Flutter Column Widget  -ویجتەکەی ستوونی فلۆتەر",
      video: 'TxgjEmjv87Q',
      wana: "28",
      content: ""),
  Pro(
      name: "بەزمانی کوردی",
      total: "Flutter Padding Widget-ویجتێکی پادکردنی فلۆتەر ",
      publisher: 'Taco Group',
      image: 'images/flutter.png',
      kurdi: "Flutter Padding Widget-ویجتێکی پادکردنی فلۆتەر ",
      video: 'c1I9QOeFGAU',
      wana: "29",
      content: ""),
  Pro(
      name: "بەزمانی کوردی",
      total: "Flutter Row Widget-ویجتەکەی ڕیزەکانی فلۆتەر",
      publisher: 'Taco Group',
      image: 'images/flutter.png',
      kurdi: "Flutter Row Widget-ویجتەکەی ڕیزەکانی فلۆتەر",
      video: '5g-KhOhoEJ8',
      wana: "30",
      content: ""),
  Pro(
      name: "بەزمانی کوردی",
      total: "Flutter Raised Button-دوگمەی بەرزکراوەی فلۆتەر",
      publisher: 'Taco Group',
      image: 'images/flutter.png',
      kurdi: "Flutter Raised Button-دوگمەی بەرزکراوەی فلۆتەر",
      video: 'UX6NMQ8i_Xg',
      wana: "31",
      content: ""),
  Pro(
      name: "بەزمانی کوردی",
      total: "Flutter Outline Button -دوگمەی هێڵکاری فلۆتەر",
      publisher: 'Taco Group',
      image: 'images/flutter.png',
      kurdi: "Flutter Outline Button -دوگمەی هێڵکاری فلۆتەر",
      video: 'vl8aUmzRlpo',
      wana: "32",
      content: ""),
  Pro(
      name: "بەزمانی کوردی",
      total: "Flutter Flat Button -دوگمەی تەختی فلۆتەر",
      publisher: 'Taco Group',
      image: 'images/flutter.png',
      kurdi: "Flutter Flat Button -دوگمەی تەختی فلۆتەر",
      video: 'lP0LBwXl9yU',
      wana: "33",
      content: ""),
  Pro(
      name: "بەزمانی کوردی",
      total: "Flutter Icon Button-دوگمەی ئایکۆنی فلۆتەر",
      publisher: 'Taco Group',
      image: 'images/flutter.png',
      kurdi: "Flutter Icon Button-دوگمەی ئایکۆنی فلۆتەر",
      video: 'EdORa91RT_s',
      wana: "34",
      content: ""),
  Pro(
      name: "بەزمانی کوردی",
      total: "Flutter Cupertino Button-دوگمەی فلۆتەر کوپەرتینۆ",
      publisher: 'Taco Group',
      image: 'images/flutter.png',
      kurdi: "Flutter Cupertino Button-دوگمەی فلۆتەر کوپەرتینۆ",
      video: 'wb5Vn2dghiI',
      wana: "35",
      content: ""),
  Pro(
      name: "بەزمانی کوردی",
      total: "Flutter Material Button-دوگمەی مادەی فلۆتەر",
      publisher: 'Taco Group',
      image: 'images/flutter.png',
      kurdi: "Flutter Material Button-دوگمەی مادەی فلاوتەر",
      video: 'NDW85cFVzkA',
      wana: "36",
      content: ""),
  Pro(
      name: "بەزمانی کوردی",
      total: "Flutter Floating Action Button-دوگمەی کرداری فلۆتینگ فلاوتەر",
      publisher: 'Taco Group',
      image: 'images/flutter.png',
      kurdi: "Flutter Floating Action Button-دوگمەی کرداری فلۆتینگ فلاوتەر",
      video: 'LOOsXx17V7I',
      wana: "37",
      content: ""),
  Pro(
      name: "بەزمانی کوردی",
      total: "Back Button And Close Button-دوگمەی پشتەوە و دوگمەی داخستنی",
      publisher: 'Taco Group',
      image: 'images/flutter.png',
      kurdi: "Back Button And Close Button-دوگمەی پشتەوە و دوگمەی داخستنی",
      video: '-gaHYB7-2Lg',
      wana: "38",
      content: ""),
  Pro(
      name: "بەزمانی کوردی",
      total: "Dropdown Button-دوگمەی دابەزین",
      publisher: 'Taco Group',
      image: 'images/flutter.png',
      kurdi: "Dropdown Button-دوگمەی دابەزین",
      video: '_Guu7GTmduk',
      wana: "39",
      content: ""),
  Pro(
      name: "بەزمانی کوردی",
      total: "Flutter Colors-ڕەنگەکانی فلۆتەر",
      publisher: 'Taco Group',
      image: 'images/flutter.png',
      kurdi: "Flutter Colors-ڕەنگەکانی فلۆتەر",
      video: 'uC-uNEpNdA8',
      wana: "40",
      content: ""),
  Pro(
      name: "بەزمانی کوردی",
      total: "Flutter Icons-ئایکۆنەکانی فلۆتەر",
      publisher: 'Taco Group',
      image: 'images/flutter.png',
      kurdi: "Flutter Icons-ئایکۆنەکانی فلۆتەر",
      video: '1E4aRvCMAmE',
      wana: "41",
      content: ""),
  Pro(
      name: "بەزمانی کوردی",
      total: "Flutter TextField Part 1-مەیدانی دەق بەشی یەکەم",
      publisher: 'Taco Group',
      image: 'images/flutter.png',
      kurdi: "Flutter TextField Part 1-مەیدانی دەق بەشی یەکەم",
      video: 'NeqB4tmuAAA',
      wana: "42",
      content: ""),
  Pro(
      name: "بەزمانی کوردی",
      total: "Flutter TextField Part 2-مەیدانی دەق بەشی دووەم",
      publisher: 'Taco Group',
      image: 'images/flutter.png',
      kurdi: "Flutter TextField Part 2-مەیدانی دەق بەشی دووەم",
      video: 'fnn7AkhyTAo',
      wana: "43",
      content: ""),
  Pro(
      name: "بەزمانی کوردی",
      total: " Text Editing Controller -کۆنتڕۆڵکەری دەستکاریکردنی دەق",
      publisher: 'Taco Group',
      image: 'images/flutter.png',
      kurdi: " Text Editing Controller -کۆنتڕۆڵکەری دەستکاریکردنی دەق",
      video: 'i86uwnLK2Nw',
      wana: "44",
      content: ""),
  Pro(
      name: "بەزمانی کوردی",
      total: "Form And TextFormField-مەیدانی فۆڕمی فۆڕم و دەق",
      publisher: 'Taco Group',
      image: 'images/flutter.png',
      kurdi: "Form And TextFormField-مەیدانی فۆڕمی فۆڕم و دەق",
      video: 'G-emMbBE3zg',
      wana: "45",
      content: ""),
  Pro(
      name: "بەزمانی کوردی",
      total: " Radio Button -دوگمەی ڕادیۆی ",
      publisher: 'Taco Group',
      image: 'images/flutter.png',
      kurdi: " Radio Button -دوگمەی ڕادیۆی ",
      video: 'A2BgjQLpGds',
      wana: "46",
      content: ""),
  Pro(
      name: "بەزمانی کوردی",
      total: "Flutter Check Box - بۆکسی هەڵبژاردن",
      publisher: 'Taco Group',
      image: 'images/flutter.png',
      kurdi: "Flutter Check Box - بۆکسی هەڵبژاردن",
      video: 'CvSWYdctDKI',
      wana: "47",
      content: ""),
  Pro(
      name: "بەزمانی کوردی",
      total: "Flutter Alert Dialog -دیالۆگی ئاگادارکردنەوەی فلۆتەر ",
      publisher: 'Taco Group',
      image: 'images/flutter.png',
      kurdi: "Flutter Alert Dialog -دیالۆگی ئاگادارکردنەوەی فلۆتەر ",
      video: '9ic9PGe1h88',
      wana: "48",
      content: ""),
  Pro(
      name: "بەزمانی کوردی",
      total: " Cupertino Alert Dialog-دیالۆگی ئاگادارکردنەوەی کوپەرتینۆ",
      publisher: 'Taco Group',
      image: 'images/flutter.png',
      kurdi: " Cupertino Alert Dialog-دیالۆگی ئاگادارکردنەوەی کوپەرتینۆ",
      video: 'ifZGalgY61g',
      wana: "49",
      content: ""),
  Pro(
      name: "بەزمانی کوردی",
      total: "Flutter show Modal Bottom Sheet-مۆداڵی لاپەڕەی خوارەوە نیشان بدە",
      publisher: 'Taco Group',
      image: 'images/flutter.png',
      kurdi: "Flutter show Modal Bottom Sheet-مۆداڵی لاپەڕەی خوارەوە نیشان بدە",
      video: 'waH0uupWU0Y',
      wana: "50",
      content: ""),
  Pro(
      name: "بەزمانی کوردی",
      total: "Flutter Snack Bar-فلۆتەر سناک بار",
      publisher: 'Taco Group',
      image: 'images/flutter.png',
      kurdi: "Flutter Snack Bar-فلۆتەر سناک بار",
      video: 'U8yyf9nwliI',
      wana: "51",
      content: ""),
  Pro(
      name: "بەزمانی کوردی",
      total: "Card widget -ویجتێکی کارت",
      publisher: 'Taco Group',
      image: 'images/flutter.png',
      kurdi: "Card widget -ویجتێکی کارت",
      video: '1Lhht99Qlx4',
      wana: "52",
      content: ""),
  Pro(
      name: "بەزمانی کوردی",
      total: " InkWell widget-ویجتەکەی ئینکوێڵ",
      publisher: 'Taco Group',
      image: 'images/flutter.png',
      kurdi: " InkWell widget-ویجتەکەی ئینکوێڵ",
      video: 'XZr7xHnPGYg',
      wana: "53",
      content: ""),
  Pro(
      name: "بەزمانی کوردی",
      total: " Slider widget -ویجتێکی سلایدەر",
      publisher: 'Taco Group',
      image: 'images/flutter.png',
      kurdi: " Slider widget -ویجتێکی سلایدەر",
      video: '3-d88gpbPQk',
      wana: "54",
      content: ""),
  Pro(
      name: "بەزمانی کوردی",
      total: " Slider with divisions and label -خلیسکە بە دابەشکردن و لیبێڵ ",
      publisher: 'Taco Group',
      image: 'images/flutter.png',
      kurdi: " Slider with divisions and label -خلیسکە بە دابەشکردن و لیبێڵ ",
      video: '5BMuVtYgb6Q',
      wana: "55",
      content: ""),
  Pro(
      name: "بەزمانی کوردی",
      total: " Wrap widget-ویجتەکەی پێچان",
      publisher: 'Taco Group',
      image: 'images/flutter.png',
      kurdi: " Wrap widget-ویجتەکەی پێچان",
      video: '8xt8msBV2-Q',
      wana: "56",
      content: ""),
  Pro(
      name: "بەزمانی کوردی",
      total: "Flutter Expanded widget-ویجتێکی فراوانکراو",
      publisher: 'Taco Group',
      image: 'images/flutter.png',
      kurdi: "Flutter Expanded widget-ویجتێکی فراوانکراو",
      video: '2OSRkH3yT7o',
      wana: "57",
      content: ""),
  Pro(
      name: "بەزمانی کوردی",
      total: "Flutter SizeBox widget-ویجتەکەی سندوقی قەبارە",
      publisher: 'Taco Group',
      image: 'images/flutter.png',
      kurdi: "Flutter SizeBox widget-ویجتەکەی سندوقی قەبارە",
      video: '1lZ8TmNCpdc',
      wana: "58",
      content: ""),
  Pro(
      name: "بەزمانی کوردی",
      total: "Flutter Stack widget -ویجتەکەی ستاک",
      publisher: 'Taco Group',
      image: 'images/flutter.png',
      kurdi: "Flutter Stack widget -ویجتەکەی ستاک",
      video: 'L-X8m9a1QYw',
      wana: "59",
      content: ""),
  Pro(
      name: "بەزمانی کوردی",
      total: "Flutter ListView widget -ویجتەکەی بینینی لیست",
      publisher: 'Taco Group',
      image: 'images/flutter.png',
      kurdi: "Flutter ListView widget -ویجتەکەی بینینی لیست",
      video: 'jsRZGcfprtk',
      wana: "60",
      content: ""),
  Pro(
      name: "بەزمانی کوردی",
      total: "GridView count -ژمارەی دیمەنی تۆڕ",
      publisher: 'Taco Group',
      image: 'images/flutter.png',
      kurdi: "GridView count -ژمارەی دیمەنی تۆڕ",
      video: 'hmTiUItZKVI',
      wana: "61",
      content: ""),
  Pro(
      name: "بەزمانی کوردی",
      total: "ListView builder -دروستکەری لیست ڤیو",
      publisher: 'Taco Group',
      image: 'images/flutter.png',
      kurdi: "ListView builder -دروستکەری لیست ڤیو",
      video: 'G1gIfy_N_Lk',
      wana: "62",
      content: ""),
  Pro(
      name: "بەزمانی کوردی",
      total: "Chip Widget -چیپ ویجت",
      publisher: 'Taco Group',
      image: 'images/flutter.png',
      kurdi: "Chip Widget -چیپ ویجت",
      video: '4nCKA0a7jJ8',
      wana: "63",
      content: ""),
  Pro(
      name: "بەزمانی کوردی",
      total: "Switch Widget -سویچ ویجت",
      publisher: 'Taco Group',
      image: 'images/flutter.png',
      kurdi: "Switch Widget -سویچ ویجت",
      video: 'HQdtBxmSkpw',
      wana: "64",
      content: ""),
  Pro(
      name: "بەزمانی کوردی",
      total: " Animation Duration Widget -ویجت بۆ ماوەی ئەنیمەیشن ",
      publisher: 'Taco Group',
      image: 'images/flutter.png',
      kurdi: " Animation Duration Widget -ویجت بۆ ماوەی ئەنیمەیشن ",
      video: 'a836nkXJFW4',
      wana: "65",
      content: ""),
  Pro(
      name: "بەزمانی کوردی",
      total: " Animation AnimatedContainer -ئەنیمەیشن کۆنتێنەری ئەنیمەیشن",
      publisher: 'Taco Group',
      image: 'images/flutter.png',
      kurdi: " Animation AnimatedContainer -ئەنیمەیشن کۆنتێنەری ئەنیمەیشن",
      video: 'aeAybt3vBlw',
      wana: "66",
      content: ""),
  Pro(
      name: "بەزمانی کوردی",
      total: " Animation AnimatedIcons -ئەنیمەیشنی ئەنیمەیشن ئایکۆنەکان ",
      publisher: 'Taco Group',
      image: 'images/flutter.png',
      kurdi: " Animation AnimatedIcons -ئەنیمەیشنی ئەنیمەیشن ئایکۆنەکان ",
      video: 'ig41X1I5rso',
      wana: "67",
      content: ""),
  Pro(
      name: "بەزمانی کوردی",
      total: " Animation AnimatedPadding -ئەنیمەیشنی ئەنیمەیشن پاددینگ",
      publisher: 'Taco Group',
      image: 'images/flutter.png',
      kurdi: " Animation AnimatedPadding -ئەنیمەیشنی ئەنیمەیشن پاددینگ",
      video: '3LJ7WMvRB-c',
      wana: "68",
      content: ""),
  Pro(
      name: "بەزمانی کوردی",
      total:
          "Animation FadeAnimatedTextKit -ئەنیمەیشن کاڵبوونەوە ئەنیمەیشنی دەق کیت",
      publisher: 'Taco Group',
      image: 'images/flutter.png',
      kurdi:
          "Animation FadeAnimatedTextKit -ئەنیمەیشن کاڵبوونەوە ئەنیمەیشنی دەق کیت",
      video: 'PnwQGPwjCR0',
      wana: "69",
      content: ""),
  Pro(
      name: "بەزمانی کوردی",
      total:
          "Animation RotateAnimatedTextKit -ئەنیمەیشن بسووڕێنە ئەنیمەیشنی دەق کیت",
      publisher: 'Taco Group',
      image: 'images/flutter.png',
      kurdi:
          "Animation RotateAnimatedTextKit -ئەنیمەیشن بسووڕێنە ئەنیمەیشنی دەق کیت",
      video: 'CSNyakOOo98',
      wana: "70",
      content: ""),
  Pro(
      name: "بەزمانی کوردی",
      total:
          "Animation TyperAnimatedTextKit - تایپکەری ئەنیمەیشن کیتی دەقی ئەنیمەیشن",
      publisher: 'Taco Group',
      image: 'images/flutter.png',
      kurdi:
          "Animation TyperAnimatedTextKit -تایپکەری ئەنیمەیشن کیتی دەقی ئەنیمەیشن",
      video: '4cyDJ3Ex9qY',
      wana: "71",
      content: ""),
  Pro(
      name: "بەزمانی کوردی",
      total:
          "Animation TypewriterAnimatedTextKit - کیتی دەقی ئەنیمەیشنی ئامێری تایپکردنی ئەنیمەیشن",
      publisher: 'Taco Group',
      image: 'images/flutter.png',
      kurdi:
          "Animation TypewriterAnimatedTextKit - کیتی دەقی ئەنیمەیشنی ئامێری تایپکردنی ئەنیمەیشن",
      video: 'R32Vm55vNSU',
      wana: "72",
      content: ""),
  Pro(
      name: "بەزمانی کوردی",
      total:
          " Animation ScaleAnimatedTextKit - پێوەرەکانی ئەنیمەیشن کیتی دەقی ئەنیمەیشن",
      publisher: 'Taco Group',
      image: 'images/flutter.png',
      kurdi:
          " Animation ScaleAnimatedTextKit - پێوەرەکانی ئەنیمەیشن کیتی دەقی ئەنیمەیشن",
      video: 'rA8KaiU7J9o',
      wana: "73",
      content: ""),
  Pro(
      name: "بەزمانی کوردی",
      total:
          "Animation ColorizeAnimatedTextKit  -ئەنیمەیشن ڕەنگکردن ئەنیمەیشنی دەق کیت ",
      publisher: 'Taco Group',
      image: 'images/flutter.png',
      kurdi:
          "Animation ColorizeAnimatedTextKit  -ئەنیمەیشن ڕەنگکردن ئەنیمەیشنی دەق کیت ",
      video: 'akLJEq3ud2c',
      wana: "74",
      content: ""),
  Pro(
      name: "بەزمانی کوردی",
      total: "Animation CarouselSlider - ئەنیمەیشنی کارۆسێل سلایدەر ",
      publisher: 'Taco Group',
      image: 'images/flutter.png',
      kurdi: "Animation CarouselSlider - ئەنیمەیشنی کارۆسێل سلایدەر ",
      video: '6plftbzj5A4',
      wana: "75",
      content: ""),
  Pro(
      name: "بەزمانی کوردی",
      total: " BasicAppBar-ئەپبارێکی بنەڕەتی",
      publisher: 'Taco Group',
      image: 'images/flutter.png',
      kurdi: " BasicAppBar-ئەپبارێکی بنەڕەتی",
      video: 'mSrFbT3i0rQ',
      wana: "76",
      content: ""),
  Pro(
      name: "بەزمانی کوردی",
      total: "PopupMenuButton -دوگمەی مێنۆی پەلەوەری",
      publisher: 'Taco Group',
      image: 'images/flutter.png',
      kurdi: "PopupMenuButton -دوگمەی مێنۆی پەلەوەری",
      video: '61TsRfrj4zU',
      wana: "77",
      content: ""),
  Pro(
      name: "بەزمانی کوردی",
      total: "BottomAppBar - خوارەوەی ئەپ بار ",
      publisher: 'Taco Group',
      image: 'images/flutter.png',
      kurdi: "BottomAppBar - خوارەوەی ئەپ بار ",
      video: 'jh985oPZRMk',
      wana: "78",
      content: ""),
  Pro(
      name: "بەزمانی کوردی",
      total: "TabBar part 1 -تاب بار بەشی یەکەم ",
      publisher: 'Taco Group',
      image: 'images/flutter.png',
      kurdi: "TabBar part 1 -تاب بار بەشی یەکەم ",
      video: 'Y753cI455EQ',
      wana: "79",
      content: ""),
  Pro(
      name: "بەزمانی کوردی",
      total: "TabBar part 2 -تاب بار بەشی دووەم ",
      publisher: 'Taco Group',
      image: 'images/flutter.png',
      kurdi: "TabBar part 2 -تاب بار بەشی دووەم ",
      video: 'dLGmXFVUT8g',
      wana: "80",
      content: ""),
  Pro(
      name: "بەزمانی کوردی",
      total: "Go To New Screen -بڕۆ بۆ شاشەی نوێ",
      publisher: 'Taco Group',
      image: 'images/flutter.png',
      kurdi: "Go To New Screen -بڕۆ بۆ شاشەی نوێ",
      video: 'V8T4f1XC-AI',
      wana: "81",
      content: ""),
  Pro(
      name: "بەزمانی کوردی",
      total: "Web Applictaion - بەرنامەی وێب ",
      publisher: 'Taco Group',
      image: 'images/flutter.png',
      kurdi: "Web Applictaion - بەرنامەی وێب ",
      video: 'nT9PYijdD6M',
      wana: "82",
      content: ""),
  Pro(
      name: "بەزمانی کوردی",
      total: "MediaQuery -میدیاکوێری",
      publisher: 'Taco Group',
      image: 'images/flutter.png',
      kurdi: "MediaQuery -میدیاکوێری",
      video: 'z58mNKnPecI',
      wana: "83",
      content: ""),
  Pro(
      name: "بەزمانی کوردی",
      total: "Sign in page Challenge -پەیجی چوونەژوورەوە چالێنج ",
      publisher: 'Taco Group',
      image: 'images/flutter.png',
      kurdi: "Sign in page Challenge -پەیجی چوونەژوورەوە چالێنج ",
      video: 'aB92y_4VHwE',
      wana: "84",
      content: ""),
  Pro(
      name: "بەزمانی کوردی",
      total: "Sign in page Challenge 2 - 2 پەیجی چوونەژوورەوە چالێنج ",
      publisher: 'Taco Group',
      image: 'images/flutter.png',
      kurdi: "Sign in page Challenge 2 - 2پەیجی چوونەژوورەوە چالێنج ",
      video: 'lqIRFQvLpBo',
      wana: "85",
      content: ""),
  Pro(
      name: "بەزمانی کوردی",
      total: " BMI challenge - تەحەدای BMI ",
      publisher: 'Taco Group',
      image: 'images/flutter.png',
      kurdi: " BMI challenge - تەحەدای BMI ",
      video: 'Ht9BlIEvB9A',
      wana: "86",
      content: ""),
  Pro(
      name: "بەزمانی کوردی",
      total: "BMI challenge Solution -تەحەدای BMI چارەسەر",
      publisher: 'Taco Group',
      image: 'images/flutter.png',
      kurdi: "BMI challenge Solution -تەحەدای BMI چارەسەر",
      video: 'K1GN_7eODOI',
      wana: "87",
      content: ""),
  Pro(
      name: "بەزمانی کوردی",
      total: "Instagram UI Kit with flutter - ئینستاگرام یوئای بە فلاتەوتەر ",
      publisher: 'Taco Group',
      image: 'images/flutter.png',
      kurdi: "Instagram UI Kit with flutter - ئینستاگرام یوئای بە فلاتەوتەر ",
      video: 'OJ67wNAKRlg',
      wana: "non",
      content: ""),
];
