class Php {
  String name;
  String total;
  String image;
  String publisher;
  String kurdi;
  String video;
  String content;
  String wana;
  Php({
    required this.name,
    required this.total,
    required this.image,
    required this.publisher,
    required this.kurdi,
    required this.video,
    required this.content,
    required this.wana,
  });
}

final php = [
  Php(
      name: "بەزمانی کوردی",
      total: ' PHP Introduction KURDISH-پێشەکی پێ ئێچ پی کوردیش',
      publisher: 'Rstacode',
      image: 'images/php.png',
      kurdi:
          'PHP Tutorials for Beginners 01 PHP Introduction KURDISH- فێرکاری پێ ئێچ پی بۆ کەسانی سەرەتایی 01پێ ئێچ پی پێشەکی کوردیش',
      video: 'HoNNjzzWNvg',
      wana: "1",
      content:
          "PHP (Hypertext Preprocessor) زمانێکی سکریپتکردنی سەرچاوە کراوە بۆ پەرەپێدانی وێب لە لایەن سێرڤەرەوە. دەتوانرێت لە HTML دا جێگیر بکرێت بۆ دروستکردنی ناوەڕۆکی داینامیکی و پشتگیری لە چەندین بنکەدراوە دەکات. لێرەدا بنەماکان دەخەینەڕوو:\n تایبەتمەندییە سەرەکییەکان:\n-Server-Side Execution**: کۆدی PHP لەسەر سێرڤەرەکە کاردەکات.\n- Cross-Platform**: کار لەسەر سیستەمی کارپێکردنی جۆراوجۆر دەکات.\n- جێگیرکراوە لە HTML**: دروستکردنی لاپەڕەی وێبی داینامیکی ئاسانە.\n- پشتگیری بنکەدراوە**: لەگەڵ بنکەدراوەی وەک MySQL یەکدەگرێتەوە."),
  Php(
      name: "بەزمانی کوردی",
      total: 'PHP Server Install - پێ ئێچ پی دامەزراندنی سێرڤەر ',
      publisher: 'Rstacode',
      image: 'images/php.png',
      kurdi:
          'PHP Tutorials for Beginners 02 PHP IDE & Server Install KURDISH-فێرکاری پێ ئێچ پی بۆ کەسانی سەرەتایی 02پێ ئێچ پی دامەزراندنی سێرڤەر کوردیش ',
      video: 'kJqSQTm1MaQ',
      wana: "2",
      content:
          "لێرەدا ڕێنماییەکی پوخت بۆ دانانی ژینگەی پەرەپێدانی PHP بە IDE و سێرڤەری ناوخۆیی دەخەینەڕوو:\n1. IDE (کۆدی ڤیژوئال ستۆدیۆ): \n- داگرتن و دامەزراندنی کۆدی ڤیژوئال ستۆدیۆ.\n- لە بازاڕی VS Code ەوە درێژکراوەی PHP دابمەزرێنە.\n2. سێرڤەری ناوخۆیی (XAMPP): \n- دابەزاندن و دامەزراندنی XAMPP لە ماڵپەڕی Apache Friends.\n- دەستپێکردنی خزمەتگوزارییەکانی Apache و MySQL لە XAMPP.\n3. ڕێکخستن:\n - فۆڵدەری پرۆژەی PHP لە VS Code بکەرەوە.\n - دەست بکە بە کۆدکردنی فایلەکانی PHP بە بەکارهێنانی VS Code بە توانای تیشک خستنە سەر ڕستەسازی و هەڵەکردن.\nئەم ڕێکخستنە ڕێگەت پێدەدات بە شێوەیەکی کارا بەرنامەکانی PHP لە ناوخۆدا پەرەپێبدەیت."),
  Php(
      name: "بەزمانی کوردی",
      total: 'PHP Variables KURDISH-پێ ئێچ پی گۆڕاوەکان کوردیش',
      publisher: 'Rstacode',
      image: 'images/php.png',
      kurdi:
          'PHP Tutorials for Beginners 03 PHP Variables KURDISH -فێرکاری پێ ئێچ پی بۆ کەسانی سەرەتایی 03پێ ئێچ پی گۆڕاوەکان کوردیش ',
      video: 'yoyC62W9IsE',
      wana: "3",
      content:
          "لە PHP دا: \n - گۆڕاوەکان داتاکان بە نیشانەی `نیشانی دۆڵار` هەڵدەگرن و ناوێک بەدوایدا دێت.\n- جۆرەکان بریتین لە ڕستە، ژمارە تەواوەکان، فلۆتەکان، بولیەکان، ڕیزبەندییەکان، شتەکان، و پووچ.\n- هەستیارن بە گەورە و بچووک و مەودای جیاوازیان هەیە: ناوخۆیی، جیهانی، و ئیستاتیک."),
  Php(
      name: "بەزمانی کوردی",
      total: 'یپێشەکی کۆرسی پی ئێچ پێ',
      publisher: 'Rstacode',
      image: 'images/php.png',
      kurdi: 'کورتە دەرباری فلاوتەر ',
      video: 'HoNNjzzWNvg',
      wana: "4",
      content: ""),
  Php(
      name: "بەزمانی کوردی",
      total: 'یپێشەکی کۆرسی پی ئێچ پێ',
      publisher: 'Rstacode',
      image: 'images/php.png',
      kurdi: 'کورتە دەرباری فلاوتەر ',
      video: 'HoNNjzzWNvg',
      wana: "5",
      content: ""),
  Php(
      name: "بەزمانی کوردی",
      total: 'یپێشەکی کۆرسی پی ئێچ پێ',
      publisher: 'Rstacode',
      image: 'images/php.png',
      kurdi: 'کورتە دەرباری فلاوتەر ',
      video: 'HoNNjzzWNvg',
      wana: "6",
      content: ""),
  Php(
      name: "بەزمانی کوردی",
      total: 'یپێشەکی کۆرسی پی ئێچ پێ',
      publisher: 'Rstacode',
      image: 'images/php.png',
      kurdi: 'کورتە دەرباری فلاوتەر ',
      video: 'HoNNjzzWNvg',
      wana: "7",
      content: ""),
  Php(
      name: "بەزمانی کوردی",
      total: 'یپێشەکی کۆرسی پی ئێچ پێ',
      publisher: 'Rstacode',
      image: 'images/php.png',
      kurdi: 'کورتە دەرباری فلاوتەر ',
      video: 'HoNNjzzWNvg',
      wana: "8",
      content: ""),
  Php(
      name: "بەزمانی کوردی",
      total: 'یپێشەکی کۆرسی پی ئێچ پێ',
      publisher: 'Rstacode',
      image: 'images/php.png',
      kurdi: 'کورتە دەرباری فلاوتەر ',
      video: 'HoNNjzzWNvg',
      wana: "9",
      content: ""),
  Php(
      name: "بەزمانی کوردی",
      total: 'یپێشەکی کۆرسی پی ئێچ پێ',
      publisher: 'Rstacode',
      image: 'images/php.png',
      kurdi: 'کورتە دەرباری فلاوتەر ',
      video: 'HoNNjzzWNvg',
      wana: "10",
      content: ""),
  Php(
      name: "بەزمانی کوردی",
      total: 'یپێشەکی کۆرسی پی ئێچ پێ',
      publisher: 'Rstacode',
      image: 'images/php.png',
      kurdi: 'کورتە دەرباری فلاوتەر ',
      video: 'HoNNjzzWNvg',
      wana: "11",
      content: ""),
  Php(
      name: "بەزمانی کوردی",
      total: 'یپێشەکی کۆرسی پی ئێچ پێ',
      publisher: 'Rstacode',
      image: 'images/php.png',
      kurdi: 'کورتە دەرباری فلاوتەر ',
      video: 'HoNNjzzWNvg',
      wana: "12",
      content: ""),
  Php(
      name: "بەزمانی کوردی",
      total: 'یپێشەکی کۆرسی پی ئێچ پێ',
      publisher: 'Rstacode',
      image: 'images/php.png',
      kurdi: 'کورتە دەرباری فلاوتەر ',
      video: 'HoNNjzzWNvg',
      wana: "13",
      content: ""),
  Php(
      name: "بەزمانی کوردی",
      total: 'یپێشەکی کۆرسی پی ئێچ پێ',
      publisher: 'Rstacode',
      image: 'images/php.png',
      kurdi: 'کورتە دەرباری فلاوتەر ',
      video: 'HoNNjzzWNvg',
      wana: "14",
      content: ""),
  Php(
      name: "بەزمانی کوردی",
      total: 'یپێشەکی کۆرسی پی ئێچ پێ',
      publisher: 'Rstacode',
      image: 'images/php.png',
      kurdi: 'کورتە دەرباری فلاوتەر ',
      video: 'HoNNjzzWNvg',
      wana: "15",
      content: ""),
  Php(
      name: "بەزمانی کوردی",
      total: 'یپێشەکی کۆرسی پی ئێچ پێ',
      publisher: 'Rstacode',
      image: 'images/php.png',
      kurdi: 'کورتە دەرباری فلاوتەر ',
      video: 'HoNNjzzWNvg',
      wana: "16",
      content: ""),
  Php(
      name: "بەزمانی کوردی",
      total: 'یپێشەکی کۆرسی پی ئێچ پێ',
      publisher: 'Rstacode',
      image: 'images/php.png',
      kurdi: 'کورتە دەرباری فلاوتەر ',
      video: 'HoNNjzzWNvg',
      wana: "17",
      content: ""),
  Php(
      name: "بەزمانی کوردی",
      total: 'یپێشەکی کۆرسی پی ئێچ پێ',
      publisher: 'Rstacode',
      image: 'images/php.png',
      kurdi: 'کورتە دەرباری فلاوتەر ',
      video: 'HoNNjzzWNvg',
      wana: "18",
      content: ""),
  Php(
      name: "بەزمانی کوردی",
      total: 'یپێشەکی کۆرسی پی ئێچ پێ',
      publisher: 'Rstacode',
      image: 'images/php.png',
      kurdi: 'کورتە دەرباری فلاوتەر ',
      video: 'HoNNjzzWNvg',
      wana: "19",
      content: ""),
  Php(
      name: "بەزمانی کوردی",
      total: 'یپێشەکی کۆرسی پی ئێچ پێ',
      publisher: 'Rstacode',
      image: 'images/php.png',
      kurdi: 'کورتە دەرباری فلاوتەر ',
      video: 'HoNNjzzWNvg',
      wana: "20",
      content: ""),
  Php(
      name: "بەزمانی کوردی",
      total: 'یپێشەکی کۆرسی پی ئێچ پێ',
      publisher: 'Rstacode',
      image: 'images/php.png',
      kurdi: 'کورتە دەرباری فلاوتەر ',
      video: 'HoNNjzzWNvg',
      wana: "21",
      content: ""),
  Php(
      name: "بەزمانی کوردی",
      total: 'یپێشەکی کۆرسی پی ئێچ پێ',
      publisher: 'Rstacode',
      image: 'images/php.png',
      kurdi: 'کورتە دەرباری فلاوتەر ',
      video: 'HoNNjzzWNvg',
      wana: "22",
      content: ""),
  Php(
      name: "بەزمانی کوردی",
      total: 'یپێشەکی کۆرسی پی ئێچ پێ',
      publisher: 'Rstacode',
      image: 'images/php.png',
      kurdi: 'کورتە دەرباری فلاوتەر ',
      video: 'HoNNjzzWNvg',
      wana: "23",
      content: ""),
  Php(
      name: "بەزمانی کوردی",
      total: 'یپێشەکی کۆرسی پی ئێچ پێ',
      publisher: 'Rstacode',
      image: 'images/php.png',
      kurdi: 'کورتە دەرباری فلاوتەر ',
      video: 'HoNNjzzWNvg',
      wana: "24",
      content: ""),
  Php(
      name: "بەزمانی کوردی",
      total: 'یپێشەکی کۆرسی پی ئێچ پێ',
      publisher: 'Rstacode',
      image: 'images/php.png',
      kurdi: 'کورتە دەرباری فلاوتەر ',
      video: 'HoNNjzzWNvg',
      wana: "25",
      content: ""),
  Php(
      name: "بەزمانی کوردی",
      total: 'یپێشەکی کۆرسی پی ئێچ پێ',
      publisher: 'Rstacode',
      image: 'images/php.png',
      kurdi: 'کورتە دەرباری فلاوتەر ',
      video: 'HoNNjzzWNvg',
      wana: "26",
      content: ""),
  Php(
      name: "بەزمانی کوردی",
      total: 'یپێشەکی کۆرسی پی ئێچ پێ',
      publisher: 'Rstacode',
      image: 'images/php.png',
      kurdi: 'کورتە دەرباری فلاوتەر ',
      video: 'HoNNjzzWNvg',
      wana: "27",
      content: ""),
  Php(
      name: "بەزمانی کوردی",
      total: 'یپێشەکی کۆرسی پی ئێچ پێ',
      publisher: 'Rstacode',
      image: 'images/php.png',
      kurdi: 'کورتە دەرباری فلاوتەر ',
      video: 'HoNNjzzWNvg',
      wana: "28",
      content: ""),
  Php(
      name: "بەزمانی کوردی",
      total: 'یپێشەکی کۆرسی پی ئێچ پێ',
      publisher: 'Rstacode',
      image: 'images/php.png',
      kurdi: 'کورتە دەرباری فلاوتەر ',
      video: 'HoNNjzzWNvg',
      wana: "29",
      content: ""),
  Php(
      name: "بەزمانی کوردی",
      total: 'یپێشەکی کۆرسی پی ئێچ پێ',
      publisher: 'Rstacode',
      image: 'images/php.png',
      kurdi: 'کورتە دەرباری فلاوتەر ',
      video: 'HoNNjzzWNvg',
      wana: "30",
      content: ""),
  Php(
      name: "بەزمانی کوردی",
      total: 'یپێشەکی کۆرسی پی ئێچ پێ',
      publisher: 'Rstacode',
      image: 'images/php.png',
      kurdi: 'کورتە دەرباری فلاوتەر ',
      video: 'HoNNjzzWNvg',
      wana: "31",
      content: ""),
  Php(
      name: "بەزمانی کوردی",
      total: 'یپێشەکی کۆرسی پی ئێچ پێ',
      publisher: 'Rstacode',
      image: 'images/php.png',
      kurdi: 'کورتە دەرباری فلاوتەر ',
      video: 'HoNNjzzWNvg',
      wana: "32",
      content: ""),
  Php(
      name: "بەزمانی کوردی",
      total: 'یپێشەکی کۆرسی پی ئێچ پێ',
      publisher: 'Rstacode',
      image: 'images/php.png',
      kurdi: 'کورتە دەرباری فلاوتەر ',
      video: 'HoNNjzzWNvg',
      wana: "33",
      content: ""),
  Php(
      name: "بەزمانی کوردی",
      total: 'یپێشەکی کۆرسی پی ئێچ پێ',
      publisher: 'Rstacode',
      image: 'images/php.png',
      kurdi: 'کورتە دەرباری فلاوتەر ',
      video: 'HoNNjzzWNvg',
      wana: "34",
      content: ""),
  Php(
      name: "بەزمانی کوردی",
      total: 'یپێشەکی کۆرسی پی ئێچ پێ',
      publisher: 'Rstacode',
      image: 'images/php.png',
      kurdi: 'کورتە دەرباری فلاوتەر ',
      video: 'HoNNjzzWNvg',
      wana: "34",
      content: ""),
  Php(
      name: "بەزمانی کوردی",
      total: 'یپێشەکی کۆرسی پی ئێچ پێ',
      publisher: 'Rstacode',
      image: 'images/php.png',
      kurdi: 'کورتە دەرباری فلاوتەر ',
      video: 'HoNNjzzWNvg',
      wana: "34",
      content: ""),
  Php(
      name: "بەزمانی کوردی",
      total: 'یپێشەکی کۆرسی پی ئێچ پێ',
      publisher: 'Rstacode',
      image: 'images/php.png',
      kurdi: 'کورتە دەرباری فلاوتەر ',
      video: 'HoNNjzzWNvg',
      wana: "34",
      content: ""),
  Php(
      name: "بەزمانی کوردی",
      total: 'یپێشەکی کۆرسی پی ئێچ پێ',
      publisher: 'Rstacode',
      image: 'images/php.png',
      kurdi: 'کورتە دەرباری فلاوتەر ',
      video: 'HoNNjzzWNvg',
      wana: "34",
      content: ""),
  Php(
      name: "بەزمانی کوردی",
      total: 'یپێشەکی کۆرسی پی ئێچ پێ',
      publisher: 'Rstacode',
      image: 'images/php.png',
      kurdi: 'کورتە دەرباری فلاوتەر ',
      video: 'HoNNjzzWNvg',
      wana: "34",
      content: ""),
  Php(
      name: "بەزمانی کوردی",
      total: 'یپێشەکی کۆرسی پی ئێچ پێ',
      publisher: 'Rstacode',
      image: 'images/php.png',
      kurdi: 'کورتە دەرباری فلاوتەر ',
      video: 'HoNNjzzWNvg',
      wana: "34",
      content: ""),
  Php(
      name: "بەزمانی کوردی",
      total: 'یپێشەکی کۆرسی پی ئێچ پێ',
      publisher: 'Rstacode',
      image: 'images/php.png',
      kurdi: 'کورتە دەرباری فلاوتەر ',
      video: 'HoNNjzzWNvg',
      wana: "34",
      content: ""),
  Php(
      name: "بەزمانی کوردی",
      total: 'یپێشەکی کۆرسی پی ئێچ پێ',
      publisher: 'Rstacode',
      image: 'images/php.png',
      kurdi: 'کورتە دەرباری فلاوتەر ',
      video: 'HoNNjzzWNvg',
      wana: "34",
      content: ""),
  Php(
      name: "بەزمانی کوردی",
      total: 'یپێشەکی کۆرسی پی ئێچ پێ',
      publisher: 'Rstacode',
      image: 'images/php.png',
      kurdi: 'کورتە دەرباری فلاوتەر ',
      video: 'HoNNjzzWNvg',
      wana: "34",
      content: ""),
  Php(
      name: "بەزمانی کوردی",
      total: 'یپێشەکی کۆرسی پی ئێچ پێ',
      publisher: 'Rstacode',
      image: 'images/php.png',
      kurdi: 'کورتە دەرباری فلاوتەر ',
      video: 'HoNNjzzWNvg',
      wana: "34",
      content: ""),
  Php(
      name: "بەزمانی کوردی",
      total: 'یپێشەکی کۆرسی پی ئێچ پێ',
      publisher: 'Rstacode',
      image: 'images/php.png',
      kurdi: 'کورتە دەرباری فلاوتەر ',
      video: 'HoNNjzzWNvg',
      wana: "34",
      content: ""),
  Php(
      name: "بەزمانی کوردی",
      total: 'یپێشەکی کۆرسی پی ئێچ پێ',
      publisher: 'Rstacode',
      image: 'images/php.png',
      kurdi: 'کورتە دەرباری فلاوتەر ',
      video: 'HoNNjzzWNvg',
      wana: "34",
      content: ""),
  Php(
      name: "بەزمانی کوردی",
      total: 'یپێشەکی کۆرسی پی ئێچ پێ',
      publisher: 'Rstacode',
      image: 'images/php.png',
      kurdi: 'کورتە دەرباری فلاوتەر ',
      video: 'HoNNjzzWNvg',
      wana: "34",
      content: ""),
  Php(
      name: "بەزمانی کوردی",
      total: 'یپێشەکی کۆرسی پی ئێچ پێ',
      publisher: 'Rstacode',
      image: 'images/php.png',
      kurdi: 'کورتە دەرباری فلاوتەر ',
      video: 'HoNNjzzWNvg',
      wana: "34",
      content: ""),
  Php(
      name: "بەزمانی کوردی",
      total: 'یپێشەکی کۆرسی پی ئێچ پێ',
      publisher: 'Rstacode',
      image: 'images/php.png',
      kurdi: 'کورتە دەرباری فلاوتەر ',
      video: 'HoNNjzzWNvg',
      wana: "34",
      content: ""),
  Php(
      name: "بەزمانی کوردی",
      total: 'یپێشەکی کۆرسی پی ئێچ پێ',
      publisher: 'Rstacode',
      image: 'images/php.png',
      kurdi: 'کورتە دەرباری فلاوتەر ',
      video: 'HoNNjzzWNvg',
      wana: "34",
      content: ""),
  Php(
      name: "بەزمانی کوردی",
      total: 'یپێشەکی کۆرسی پی ئێچ پێ',
      publisher: 'Rstacode',
      image: 'images/php.png',
      kurdi: 'کورتە دەرباری فلاوتەر ',
      video: 'HoNNjzzWNvg',
      wana: "34",
      content: ""),
  Php(
      name: "بەزمانی کوردی",
      total: 'یپێشەکی کۆرسی پی ئێچ پێ',
      publisher: 'Rstacode',
      image: 'images/php.png',
      kurdi: 'کورتە دەرباری فلاوتەر ',
      video: 'HoNNjzzWNvg',
      wana: "34",
      content: ""),
  Php(
      name: "بەزمانی کوردی",
      total: 'یپێشەکی کۆرسی پی ئێچ پێ',
      publisher: 'Rstacode',
      image: 'images/php.png',
      kurdi: 'کورتە دەرباری فلاوتەر ',
      video: 'HoNNjzzWNvg',
      wana: "34",
      content: ""),
  Php(
      name: "بەزمانی کوردی",
      total: 'یپێشەکی کۆرسی پی ئێچ پێ',
      publisher: 'Rstacode',
      image: 'images/php.png',
      kurdi: 'کورتە دەرباری فلاوتەر ',
      video: 'HoNNjzzWNvg',
      wana: "34",
      content: ""),
  Php(
      name: "بەزمانی کوردی",
      total: 'یپێشەکی کۆرسی پی ئێچ پێ',
      publisher: 'Rstacode',
      image: 'images/php.png',
      kurdi: 'کورتە دەرباری فلاوتەر ',
      video: 'HoNNjzzWNvg',
      wana: "34",
      content: ""),
  Php(
      name: "بەزمانی کوردی",
      total: 'یپێشەکی کۆرسی پی ئێچ پێ',
      publisher: 'Rstacode',
      image: 'images/php.png',
      kurdi: 'کورتە دەرباری فلاوتەر ',
      video: 'HoNNjzzWNvg',
      wana: "34",
      content: ""),
  Php(
      name: "بەزمانی کوردی",
      total: 'یپێشەکی کۆرسی پی ئێچ پێ',
      publisher: 'Rstacode',
      image: 'images/php.png',
      kurdi: 'کورتە دەرباری فلاوتەر ',
      video: 'HoNNjzzWNvg',
      wana: "34",
      content: ""),
  Php(
      name: "بەزمانی کوردی",
      total: 'یپێشەکی کۆرسی پی ئێچ پێ',
      publisher: 'Rstacode',
      image: 'images/php.png',
      kurdi: 'کورتە دەرباری فلاوتەر ',
      video: 'HoNNjzzWNvg',
      wana: "34",
      content: ""),
  Php(
      name: "بەزمانی کوردی",
      total: 'یپێشەکی کۆرسی پی ئێچ پێ',
      publisher: 'Rstacode',
      image: 'images/php.png',
      kurdi: 'کورتە دەرباری فلاوتەر ',
      video: 'HoNNjzzWNvg',
      wana: "34",
      content: ""),
  Php(
      name: "بەزمانی کوردی",
      total: 'یپێشەکی کۆرسی پی ئێچ پێ',
      publisher: 'Rstacode',
      image: 'images/php.png',
      kurdi: 'کورتە دەرباری فلاوتەر ',
      video: 'HoNNjzzWNvg',
      wana: "34",
      content: ""),
  Php(
      name: "بەزمانی کوردی",
      total: 'یپێشەکی کۆرسی پی ئێچ پێ',
      publisher: 'Rstacode',
      image: 'images/php.png',
      kurdi: 'کورتە دەرباری فلاوتەر ',
      video: 'HoNNjzzWNvg',
      wana: "34",
      content: ""),
  Php(
      name: "بەزمانی کوردی",
      total: 'یپێشەکی کۆرسی پی ئێچ پێ',
      publisher: 'Rstacode',
      image: 'images/php.png',
      kurdi: 'کورتە دەرباری فلاوتەر ',
      video: 'HoNNjzzWNvg',
      wana: "34",
      content: ""),
  Php(
      name: "بەزمانی کوردی",
      total: 'یپێشەکی کۆرسی پی ئێچ پێ',
      publisher: 'Rstacode',
      image: 'images/php.png',
      kurdi: 'کورتە دەرباری فلاوتەر ',
      video: 'HoNNjzzWNvg',
      wana: "34",
      content: ""),
  Php(
      name: "بەزمانی کوردی",
      total: 'یپێشەکی کۆرسی پی ئێچ پێ',
      publisher: 'Rstacode',
      image: 'images/php.png',
      kurdi: 'کورتە دەرباری فلاوتەر ',
      video: 'HoNNjzzWNvg',
      wana: "34",
      content: ""),
  Php(
      name: "بەزمانی کوردی",
      total: 'یپێشەکی کۆرسی پی ئێچ پێ',
      publisher: 'Rstacode',
      image: 'images/php.png',
      kurdi: 'کورتە دەرباری فلاوتەر ',
      video: 'HoNNjzzWNvg',
      wana: "34",
      content: ""),
  Php(
      name: "بەزمانی کوردی",
      total: 'یپێشەکی کۆرسی پی ئێچ پێ',
      publisher: 'Rstacode',
      image: 'images/php.png',
      kurdi: 'کورتە دەرباری فلاوتەر ',
      video: 'HoNNjzzWNvg',
      wana: "34",
      content: ""),
  Php(
      name: "بەزمانی کوردی",
      total: 'یپێشەکی کۆرسی پی ئێچ پێ',
      publisher: 'Rstacode',
      image: 'images/php.png',
      kurdi: 'کورتە دەرباری فلاوتەر ',
      video: 'HoNNjzzWNvg',
      wana: "34",
      content: ""),
  Php(
      name: "بەزمانی کوردی",
      total: 'یپێشەکی کۆرسی پی ئێچ پێ',
      publisher: 'Rstacode',
      image: 'images/php.png',
      kurdi: 'کورتە دەرباری فلاوتەر ',
      video: 'HoNNjzzWNvg',
      wana: "34",
      content: ""),
  Php(
      name: "بەزمانی کوردی",
      total: 'یپێشەکی کۆرسی پی ئێچ پێ',
      publisher: 'Rstacode',
      image: 'images/php.png',
      kurdi: 'کورتە دەرباری فلاوتەر ',
      video: 'HoNNjzzWNvg',
      wana: "34",
      content: ""),
  Php(
      name: "بەزمانی کوردی",
      total: 'یپێشەکی کۆرسی پی ئێچ پێ',
      publisher: 'Rstacode',
      image: 'images/php.png',
      kurdi: 'کورتە دەرباری فلاوتەر ',
      video: 'HoNNjzzWNvg',
      wana: "34",
      content: ""),
  Php(
      name: "بەزمانی کوردی",
      total: 'یپێشەکی کۆرسی پی ئێچ پێ',
      publisher: 'Rstacode',
      image: 'images/php.png',
      kurdi: 'کورتە دەرباری فلاوتەر ',
      video: 'HoNNjzzWNvg',
      wana: "34",
      content: ""),
  Php(
      name: "بەزمانی کوردی",
      total: 'یپێشەکی کۆرسی پی ئێچ پێ',
      publisher: 'Rstacode',
      image: 'images/php.png',
      kurdi: 'کورتە دەرباری فلاوتەر ',
      video: 'HoNNjzzWNvg',
      wana: "34",
      content: ""),
  Php(
      name: "بەزمانی کوردی",
      total: 'یپێشەکی کۆرسی پی ئێچ پێ',
      publisher: 'Rstacode',
      image: 'images/php.png',
      kurdi: 'کورتە دەرباری فلاوتەر ',
      video: 'HoNNjzzWNvg',
      wana: "34",
      content: ""),
  Php(
      name: "بەزمانی کوردی",
      total: 'یپێشەکی کۆرسی پی ئێچ پێ',
      publisher: 'Rstacode',
      image: 'images/php.png',
      kurdi: 'کورتە دەرباری فلاوتەر ',
      video: 'HoNNjzzWNvg',
      wana: "34",
      content: ""),
  Php(
      name: "بەزمانی کوردی",
      total: 'یپێشەکی کۆرسی پی ئێچ پێ',
      publisher: 'Rstacode',
      image: 'images/php.png',
      kurdi: 'کورتە دەرباری فلاوتەر ',
      video: 'HoNNjzzWNvg',
      wana: "34",
      content: ""),
  Php(
      name: "بەزمانی کوردی",
      total: 'یپێشەکی کۆرسی پی ئێچ پێ',
      publisher: 'Rstacode',
      image: 'images/php.png',
      kurdi: 'کورتە دەرباری فلاوتەر ',
      video: 'HoNNjzzWNvg',
      wana: "34",
      content: ""),
  Php(
      name: "بەزمانی کوردی",
      total: 'یپێشەکی کۆرسی پی ئێچ پێ',
      publisher: 'Rstacode',
      image: 'images/php.png',
      kurdi: 'کورتە دەرباری فلاوتەر ',
      video: 'HoNNjzzWNvg',
      wana: "34",
      content: ""),
  Php(
      name: "بەزمانی کوردی",
      total: 'یپێشەکی کۆرسی پی ئێچ پێ',
      publisher: 'Rstacode',
      image: 'images/php.png',
      kurdi: 'کورتە دەرباری فلاوتەر ',
      video: 'HoNNjzzWNvg',
      wana: "34",
      content: ""),
  Php(
      name: "بەزمانی کوردی",
      total: 'یپێشەکی کۆرسی پی ئێچ پێ',
      publisher: 'Rstacode',
      image: 'images/php.png',
      kurdi: 'کورتە دەرباری فلاوتەر ',
      video: 'HoNNjzzWNvg',
      wana: "34",
      content: ""),
  Php(
      name: "بەزمانی کوردی",
      total: 'یپێشەکی کۆرسی پی ئێچ پێ',
      publisher: 'Rstacode',
      image: 'images/php.png',
      kurdi: 'کورتە دەرباری فلاوتەر ',
      video: 'HoNNjzzWNvg',
      wana: "34",
      content: ""),
  Php(
      name: "بەزمانی کوردی",
      total: 'یپێشەکی کۆرسی پی ئێچ پێ',
      publisher: 'Rstacode',
      image: 'images/php.png',
      kurdi: 'کورتە دەرباری فلاوتەر ',
      video: 'HoNNjzzWNvg',
      wana: "34",
      content: ""),
  Php(
      name: "بەزمانی کوردی",
      total: 'یپێشەکی کۆرسی پی ئێچ پێ',
      publisher: 'Rstacode',
      image: 'images/php.png',
      kurdi: 'کورتە دەرباری فلاوتەر ',
      video: 'HoNNjzzWNvg',
      wana: "34",
      content: ""),
  Php(
      name: "بەزمانی کوردی",
      total: 'یپێشەکی کۆرسی پی ئێچ پێ',
      publisher: 'Rstacode',
      image: 'images/php.png',
      kurdi: 'کورتە دەرباری فلاوتەر ',
      video: 'HoNNjzzWNvg',
      wana: "34",
      content: ""),
  Php(
      name: "بەزمانی کوردی",
      total: 'یپێشەکی کۆرسی پی ئێچ پێ',
      publisher: 'Rstacode',
      image: 'images/php.png',
      kurdi: 'کورتە دەرباری فلاوتەر ',
      video: 'HoNNjzzWNvg',
      wana: "34",
      content: ""),
  Php(
      name: "بەزمانی کوردی",
      total: 'یپێشەکی کۆرسی پی ئێچ پێ',
      publisher: 'Rstacode',
      image: 'images/php.png',
      kurdi: 'کورتە دەرباری فلاوتەر ',
      video: 'HoNNjzzWNvg',
      wana: "34",
      content: ""),
  Php(
      name: "بەزمانی کوردی",
      total: 'یپێشەکی کۆرسی پی ئێچ پێ',
      publisher: 'Rstacode',
      image: 'images/php.png',
      kurdi: 'کورتە دەرباری فلاوتەر ',
      video: 'HoNNjzzWNvg',
      wana: "34",
      content: ""),
  Php(
      name: "بەزمانی کوردی",
      total: 'یپێشەکی کۆرسی پی ئێچ پێ',
      publisher: 'Rstacode',
      image: 'images/php.png',
      kurdi: 'کورتە دەرباری فلاوتەر ',
      video: 'HoNNjzzWNvg',
      wana: "34",
      content: ""),
  Php(
      name: "بەزمانی کوردی",
      total: 'یپێشەکی کۆرسی پی ئێچ پێ',
      publisher: 'Rstacode',
      image: 'images/php.png',
      kurdi: 'کورتە دەرباری فلاوتەر ',
      video: 'HoNNjzzWNvg',
      wana: "34",
      content: ""),
  Php(
      name: "بەزمانی کوردی",
      total: 'یپێشەکی کۆرسی پی ئێچ پێ',
      publisher: 'Rstacode',
      image: 'images/php.png',
      kurdi: 'کورتە دەرباری فلاوتەر ',
      video: 'HoNNjzzWNvg',
      wana: "34",
      content: ""),
  Php(
      name: "بەزمانی کوردی",
      total: 'یپێشەکی کۆرسی پی ئێچ پێ',
      publisher: 'Rstacode',
      image: 'images/php.png',
      kurdi: 'کورتە دەرباری فلاوتەر ',
      video: 'HoNNjzzWNvg',
      wana: "34",
      content: ""),
  Php(
      name: "بەزمانی کوردی",
      total: 'یپێشەکی کۆرسی پی ئێچ پێ',
      publisher: 'Rstacode',
      image: 'images/php.png',
      kurdi: 'کورتە دەرباری فلاوتەر ',
      video: 'HoNNjzzWNvg',
      wana: "34",
      content: ""),
  Php(
      name: "بەزمانی کوردی",
      total: 'یپێشەکی کۆرسی پی ئێچ پێ',
      publisher: 'Rstacode',
      image: 'images/php.png',
      kurdi: 'کورتە دەرباری فلاوتەر ',
      video: 'HoNNjzzWNvg',
      wana: "34",
      content: ""),
  Php(
      name: "بەزمانی کوردی",
      total: 'یپێشەکی کۆرسی پی ئێچ پێ',
      publisher: 'Rstacode',
      image: 'images/php.png',
      kurdi: 'کورتە دەرباری فلاوتەر ',
      video: 'HoNNjzzWNvg',
      wana: "34",
      content: ""),
  Php(
      name: "بەزمانی کوردی",
      total: 'یپێشەکی کۆرسی پی ئێچ پێ',
      publisher: 'Rstacode',
      image: 'images/php.png',
      kurdi: 'کورتە دەرباری فلاوتەر ',
      video: 'HoNNjzzWNvg',
      wana: "34",
      content: ""),
  Php(
      name: "بەزمانی کوردی",
      total: 'یپێشەکی کۆرسی پی ئێچ پێ',
      publisher: 'Rstacode',
      image: 'images/php.png',
      kurdi: 'کورتە دەرباری فلاوتەر ',
      video: 'HoNNjzzWNvg',
      wana: "34",
      content: ""),
  Php(
      name: "بەزمانی کوردی",
      total: 'یپێشەکی کۆرسی پی ئێچ پێ',
      publisher: 'Rstacode',
      image: 'images/php.png',
      kurdi: 'کورتە دەرباری فلاوتەر ',
      video: 'HoNNjzzWNvg',
      wana: "34",
      content: ""),
  Php(
      name: "بەزمانی کوردی",
      total: 'یپێشەکی کۆرسی پی ئێچ پێ',
      publisher: 'Rstacode',
      image: 'images/php.png',
      kurdi: 'کورتە دەرباری فلاوتەر ',
      video: 'HoNNjzzWNvg',
      wana: "34",
      content: ""),
  Php(
      name: "بەزمانی کوردی",
      total: 'یپێشەکی کۆرسی پی ئێچ پێ',
      publisher: 'Rstacode',
      image: 'images/php.png',
      kurdi: 'کورتە دەرباری فلاوتەر ',
      video: 'HoNNjzzWNvg',
      wana: "34",
      content: ""),
  Php(
      name: "بەزمانی کوردی",
      total: 'یپێشەکی کۆرسی پی ئێچ پێ',
      publisher: 'Rstacode',
      image: 'images/php.png',
      kurdi: 'کورتە دەرباری فلاوتەر ',
      video: 'HoNNjzzWNvg',
      wana: "34",
      content: ""),
  Php(
      name: "بەزمانی کوردی",
      total: 'یپێشەکی کۆرسی پی ئێچ پێ',
      publisher: 'Rstacode',
      image: 'images/php.png',
      kurdi: 'کورتە دەرباری فلاوتەر ',
      video: 'HoNNjzzWNvg',
      wana: "34",
      content: ""),
  Php(
      name: "بەزمانی کوردی",
      total: 'یپێشەکی کۆرسی پی ئێچ پێ',
      publisher: 'Rstacode',
      image: 'images/php.png',
      kurdi: 'کورتە دەرباری فلاوتەر ',
      video: 'HoNNjzzWNvg',
      wana: "34",
      content: ""),
  Php(
      name: "بەزمانی کوردی",
      total: 'یپێشەکی کۆرسی پی ئێچ پێ',
      publisher: 'Rstacode',
      image: 'images/php.png',
      kurdi: 'کورتە دەرباری فلاوتەر ',
      video: 'HoNNjzzWNvg',
      wana: "34",
      content: ""),
  Php(
      name: "بەزمانی کوردی",
      total: 'یپێشەکی کۆرسی پی ئێچ پێ',
      publisher: 'Rstacode',
      image: 'images/php.png',
      kurdi: 'کورتە دەرباری فلاوتەر ',
      video: 'HoNNjzzWNvg',
      wana: "34",
      content: ""),
];



/*
import 'package:flutter/material.dart';

class Flatr {
  String name, total, image, publisher, wana, zhmara;
  Flatr(this.name, this.total, this.wana, this.zhmara, this.publisher,
      this.image);
  static map(Widget Function(dynamic all) parama0) {}
}

List<Flatr> flatr = [
  Flatr("پێشەکی کۆرسی فلاوتەربی", "بەزمانی کوردی", 'وانەی', 'یەکەم
      'Rstacode', 'images/flutter.png'),
  Flatr("پێشەکی کۆرسی فلاوتەربی", "بەزمانی کوردی", 'وانەی', 'یەکەم',
      'Rstacode', 'images/flutter.png'),
  Flatr("پێشەکی کۆرسی فلاوتەربی", "بەزمانی کوردی", 'وانەی', 'یەکەم',
      'Rstacode', 'images/flutter.png'),
  Flatr("پێشەکی کۆرسی فلاوتەربی", "بەزمانی کوردی", 'وانەی', 'یەکەم',
      'Rstacode', 'images/flutter.png'),
];
'*/