class Sharb {
  String name;
  String total;
  String image;
  String publisher;
  String kurdi;
  String video;
  String wana;
  String content;

  Sharb({
    required this.name,
    required this.total,
    required this.image,
    required this.publisher,
    required this.kurdi,
    required this.video,
    required this.wana,
    required this.content,
  });
}

final sharb = [
  Sharb(
      name: "بەزمانی کوردی",
      total: 'Button and Label فێربوونی سی شارپ بە کوردی وانەی',
      publisher: 'ferbun u zanst',
      image: 'images/c#.png',
      kurdi: 'Button and Label فێربوونی سی شارپ بە کوردی وانەی',
      video: 'Tq-FP66mnUk',
      wana: "1",
      content:
        "زمانی جاڤا، هەرچەندە گریمانەییە، بەڵام وەک زمانێکی مۆدێرن و ئاست بەرزی بەرنامەسازی پێشبینی دەکرێت کە بۆ سادەیی و کارایی و گونجانی نێوان پلاتفۆرمەکان داڕێژراوە. سوودە سەرەکییەکانی بریتین لە:\n"
        "1. سادەیی و خوێندنەوە: ڕستەسازییەکی ئاسان بۆ خوێندنەوە کە هەڵەکان کەمدەکاتەوە و ئۆنبۆردکردن خێراتر دەکات.\n"
        "2. کتێبخانەی ستانداردی بەهێز: کاراییە گشتگیرەکانی ناوەوە بۆ کەمکردنەوەی وابەستەیی بە کتێبخانە دەرەکییەکان.\n"
        "3. گونجانی نێوان پلاتفۆرمەکان: کارکردنی بێ کێشە لە سەرانسەری سیستەمی کارپێکردنی جیاوازدا.\n"
        "4. کارایی بەرزکراوە: باشتر کراوە بۆ بەڕێوەبردنی کارامەی بیرگە و جێبەجێکردنی خێرا.\n"
        "5. تایپکردنی بەهێز لەگەڵ نەرمی: تایپکردنی بەهێز لەگەڵ دەرئەنجامدانی جۆر و تایپکردنی داینامیکی تێکەڵ دەکات.\n"
        "6. پشتگیری هاوکاتی و هاوتەریبی: تایبەتمەندییە بنیات نراوەکان بۆ بەرنامە فرە ڕەگەکانی قەبارەدار.\n"
        "7. ئامرازەکانی پەرەپێدانی مۆدێرن: پشتگیری دەکرێت لەلایەن IDE و دیباگەر و ئامرازەکانی تری بەرزکردنەوەی بەرهەمهێنان.\n"
        "8. سەلامەتی و ئاسایش: جەخت لەسەر سەلامەتی بیرگە، سەلامەتی پووچ و پاراستن لە لاوازییەکان دەکاتەوە.\n"
        "9. کۆمەڵگە و ئیکۆسیستەم: کۆمەڵگەی گەشەپێدەری زیندوو کە کتێبخانە و چوارچێوەی بەرفراوانی هەیە.\n"
        "10. کارکردنی یەکتر: یەکگرتنی بێ کێشە لەگەڵ زمان و سیستەمەکانی تر.\n",
  ),
  Sharb(
      name: "بەزمانی کوردی",
      total: 'TextBox فێربوونی سی شارپ بە کوردی وانەی دووەم',
      publisher: 'ferbun u zanst',
      image: 'images/c#.png',
      kurdi: 'TextBox فێربوونی سی شارپ بە کوردی وانەی دووەم',
      video: 'r_xT5GS3EuA',
      wana: "2",
      content: ""),
  Sharb(
      name: "بەزمانی کوردی",
      total: 'ComboBox فێربوونی سی شارپ بە کوردی وانەی سێیەم',
      publisher: 'ferbun u zanst',
      image: 'images/c#.png',
      kurdi: 'ComboBox فێربوونی سی شارپ بە کوردی وانەی سێیەم',
      video: 'or4ys8lkj3w',
      wana: "3",
      content: ""),
  Sharb(
      name: "بەزمانی کوردی",
      total: 'Panel فێربوونی سی شارپ بە کوردی وانەی چوارەم',
      publisher: 'ferbun u zanst',
      image: 'images/c#.png',
      kurdi: 'Panel فێربوونی سی شارپ بە کوردی وانەی چوارەم',
      video: 'FrysdJjYbLQ',
      wana: "4",
      content: ""),
  Sharb(
      name: "بەزمانی کوردی",
      total: 'CheckBox فێربوونی سی شارپ بە کوردی وانەی پێنجەم',
      publisher: 'ferbun u zanst',
      image: 'images/c#.png',
      kurdi: 'CheckBox فێربوونی سی شارپ بە کوردی وانەی پێنجەم',
      video: 'ZhyFcRNRoBc',
      wana: "5",
      content: ""),
  Sharb(
      name: "بەزمانی کوردی",
      total: 'Login DataBase فێربوونی سی شارپ بە کوردی وانەی',
      publisher: 'ferbun u zanst',
      image: 'images/c#.png',
      kurdi: 'Login DataBase فێربوونی سی شارپ بە کوردی وانەی',
      video: 'lW6CHLdNEEY',
      wana: "6",
      content: ""),
  Sharb(
      name: "بەزمانی کوردی",
      total: 'DabataBae && DataGridView && View && Insert',
      publisher: 'ferbun u zanst',
      image: 'images/c#.png',
      kurdi: 'DabataBae && DataGridView && View && Insert',
      video: 'RM0R_1uA0Fc',
      wana: "7",
      content: ""),
  Sharb(
      name: "بەزمانی کوردی",
      total: 'DabataBase && DataGridView && Delete',
      publisher: 'ferbun u zanst',
      image: 'images/c#.png',
      kurdi: 'DabataBase && DataGridView && Delete',
      video: '7mL2-wLaxGM',
      wana: "8",
      content: ""),
  Sharb(
      name: "بەزمانی کوردی",
      total: ' DabataBase && DataGridView && Update',
      publisher: 'ferbun u zanst',
      image: 'images/c#.png',
      kurdi: ' DabataBase && DataGridView && Update',
      video: 'NZTaLI-aP_8',
      wana: "9",
      content: ""),
  Sharb(
      name: "بەزمانی کوردی",
      total: ' DabataBase && DataGridView && Search',
      publisher: 'ferbun u zanst',
      image: 'images/c#.png',
      kurdi: ' DabataBase && DataGridView && Search',
      video: 'oIjTx3TZdew',
      wana: "10",
      content: ""),
  Sharb(
      name: "بەزمانی کوردی",
      total: 'OpenFileDialog',
      publisher: 'ferbun u zanst',
      image: 'images/c#.png',
      kurdi: 'OpenFileDialog',
      video: 'K-WD8nqZous',
      wana: "11",
      content: ""),
  Sharb(
      name: "بەزمانی کوردی",
      total: 'Erroor Provider-دابینکەری هەڵە',
      publisher: 'ferbun u zanst',
      image: 'images/c#.png',
      kurdi: 'Erroor Provider -دابینکەری هەڵە  ',
      video: 'KnqqNN23njs',
      wana: "12",
      content: ""),
  Sharb(
      name: "بەزمانی کوردی",
      total:
          ' Error Provider To Login System-دابینکەری هەڵە بۆ سیستەمی چوونەژوورەوە',
      publisher: 'ferbun u zanst',
      image: 'images/c#.png',
      kurdi:
          ' Error Provider To Login System-دابینکەری هەڵە بۆ سیستەمی چوونەژوورەوە',
      video: '6R_yKC53_oE',
      wana: "13",
      content: ""),
  Sharb(
      name: "بەزمانی کوردی",
      total: 'DataGridView Multiple-بینینی تۆڕی داتا چەندە',
      publisher: 'ferbun u zanst',
      image: 'images/c#.png',
      kurdi: 'DataGridView Multiple-بینینی تۆڕی داتا چەندە',
      video: 'gWlYbvqpNLg',
      wana: "14",
      content: ""),
  Sharb(
      name: "بەزمانی کوردی",
      total: ' Dictionary English to Kurdish-فەرهەنگ ئینگلیزی بۆ کوردی',
      publisher: 'ferbun u zanst',
      image: 'images/c#.png',
      kurdi: ' Dictionary English to Kurdish-فەرهەنگ ئینگلیزی بۆ کوردی',
      video: 'EPM19ekzmOc',
      wana: "15",
      content: ""),
  Sharb(
      name: "بەزمانی کوردی",
      total: 'Timer -تایمەر',
      publisher: 'ferbun u zanst',
      image: 'images/c#.png',
      kurdi: 'Timer -تایمەر',
      video: 'SoOQWBM2TWc',
      wana: "16",
      content: ""),
  Sharb(
      name: "بەزمانی کوردی",
      total: 'TreeView -تریڤیو',
      publisher: 'ferbun u zanst',
      image: 'images/c#.png',
      kurdi: 'TreeView - تریڤیو ',
      video: '1JmHCLi4U4k',
      wana: "17",
      content: ""),
  Sharb(
      name: "بەزمانی کوردی",
      total: 'ListBox -سندوقی لیست',
      publisher: 'ferbun u zanst',
      image: 'images/c#.png',
      kurdi: 'ListBox - سندوقی لیست',
      video: 'gVfyeI-GsCQ',
      wana: "18",
      content: ""),
  Sharb(
      name: "بەزمانی کوردی",
      total: ' Search Between ComboBox-گەڕان لە نێوان کۆمبۆ بۆکس',
      publisher: 'ferbun u zanst',
      image: 'images/c#.png',
      kurdi: ' Search Between ComboBox-گەڕان لە نێوان کۆمبۆ بۆکس',
      video: 'xBhQfp0Hm_M',
      wana: "19",
      content: ""),
  Sharb(
      name: "بەزمانی کوردی",
      total: ' DataBase && Sql Command',
      publisher: 'ferbun u zanst',
      image: 'images/c#.png',
      kurdi: ' DataBase && Sql Command',
      video: '18CXKAeHkwo',
      wana: "20",
      content: ""),
  Sharb(
      name: "بەزمانی کوردی",
      total: 'DataBase && Sql Command && delete',
      publisher: 'ferbun u zanst',
      image: 'images/c#.png',
      kurdi: 'DataBase && Sql Command && delete',
      video: 'jUMiiVXBuIw',
      wana: "21",
      content: ""),
  Sharb(
      name: "بەزمانی کوردی",
      total: 'DataBase && Sql Command && Update ',
      publisher: 'ferbun u zanst',
      image: 'images/c#.png',
      kurdi: 'DataBase && Sql Command && Update ',
      video: 'ZhREzZ8JApQ',
      wana: "22",
      content: ""),
  Sharb(
      name: "بەزمانی کوردی",
      total: 'DataBase && Sql Command && Search',
      publisher: 'ferbun u zanst',
      image: 'images/c#.png',
      kurdi: 'DataBase && Sql Command && Search',
      video: 'xtNmu3JpF24',
      wana: "23",
      content: ""),
  Sharb(
      name: "بەزمانی کوردی",
      total: 'DataBase && Sql Command && DataGridView ',
      publisher: 'ferbun u zanst',
      image: 'images/c#.png',
      kurdi: 'DataBase && Sql Command && DataGridView ',
      video: 'y_Gl2EHJJxw',
      wana: "24",
      content: ""),
  Sharb(
      name: "بەزمانی کوردی",
      total: ' Sql Command && DataGridView && Delete',
      publisher: 'ferbun u zanst',
      image: 'images/c#.png',
      kurdi: ' Sql Command && DataGridView && Delete',
      video: '5jYgK2gh5xA',
      wana: "25",
      content: ""),
  Sharb(
      name: "بەزمانی کوردی",
      total: 'Sql Command && DataGridView && Update',
      publisher: 'ferbun u zanst',
      image: 'images/c#.png',
      kurdi: 'Sql Command && DataGridView && Update',
      video: 'cLRe4FbUrNE',
      wana: "26",
      content: ""),
  Sharb(
      name: "بەزمانی کوردی",
      total: 'colorDialog-دیالۆگی ڕەنگەکان',
      publisher: 'ferbun u zanst',
      image: 'images/c#.png',
      kurdi: 'colorDialog-دیالۆگی ڕەنگەکان',
      video: 'XMQphQGfR-M',
      wana: "27",
      content: ""),
  Sharb(
      name: "بەزمانی کوردی",
      total: 'radio button-دوگمەی ڕادیۆ',
      publisher: 'ferbun u zanst',
      image: 'images/c#.png',
      kurdi: 'radio button-دوگمەی ڕادیۆ',
      video: 'vTXRMRC3q30',
      wana: "28",
      content: ""),
  Sharb(
      name: "بەزمانی کوردی",
      total: 'ProcessBar- پێشکەوتن بار',
      publisher: 'ferbun u zanst',
      image: 'images/c#.png',
      kurdi: 'ProcessBar- پێشکەوتن بار',
      video: 'D3gl_wYjmg',
      wana: "29",
      content: ""),
  Sharb(
      name: "بەزمانی کوردی",
      total: 'Background worker-باکگراوند کرێکار',
      publisher: 'ferbun u zanst',
      image: 'images/c#.png',
      kurdi: 'Background worker-باکگراوند کرێکار',
      video: 'Bv8Q_0cHYOo',
      wana: "30",
      content: ""),
  Sharb(
      name: "بەزمانی کوردی",
      total: 'Backgrund workar-باکگراوند کرێکار',
      publisher: 'ferbun u zanst',
      image: 'images/c#.png',
      kurdi: 'checkedListBox- باکگراوند کرێکار',
      video: '9HKW7ns1x2Q',
      wana: "31",
      content: ""),
  Sharb(
      name: "بەزمانی کوردی",
      total: 'DateTimePicker-بەروارکات هەڵبژاردن-',
      publisher: 'ferbun u zanst',
      image: 'images/c#.png',
      kurdi: 'DateTimePicker-بەروارکات هەڵبژاردن-',
      video: 'QxbS5X1_G3k',
      wana: "32",
      content: ""),
  Sharb(
      name: "بەزمانی کوردی",
      total: 'SHut Down And Restart-کوژاندنەوە و دووبارە دەستپێکردنەوە  ',
      publisher: 'ferbun u zanst',
      image: 'images/c#.png',
      kurdi: 'SHut Down And Restart- کوژاندنەوە و دووبارە دەستپێکردنەوە  ',
      video: '7_9sPH2YrO8',
      wana: "33",
      content: ""),
  Sharb(
      name: "بەزمانی کوردی",
      total: 'datagridviwe-داتاگریدڤیو',
      publisher: 'ferbun u zanst',
      image: 'images/c#.png',
      kurdi: 'datagridviwe-داتاگریدڤیو',
      video: 'TJH9zan6sdk',
      wana: "34",
      content: ""),
  Sharb(
      name: "بەزمانی کوردی",
      total: 'skell servics-خزمەتگوزارییەکانی سکێل',
      publisher: 'ferbun u zanst',
      image: 'images/c#.png',
      kurdi: 'skell servics-خزمەتگوزارییەکانی سکێل',
      video: 'f0SjYVZdTos',
      wana: "35",
      content: ""),
  Sharb(
      name: "بەزمانی کوردی",
      total: 'insert-تێکردن',
      publisher: 'ferbun u zanst',
      image: 'images/c#.png',
      kurdi: 'insert-تێکردن',
      video: 'HYS8hQHTsf8',
      wana: "36",
      content: ""),
  Sharb(
      name: "بەزمانی کوردی",
      total: 'deleat -سڕینەوە',
      publisher: 'ferbun u zanst',
      image: 'images/c#.png',
      kurdi: 'deleat -سڕینەوە',
      video: 'Ln70Oy2g7ds',
      wana: "37",
      content: ""),
  Sharb(
      name: "بەزمانی کوردی",
      total: 'update-نوێکردنەوە',
      publisher: 'ferbun u zanst',
      image: 'images/c#.png',
      kurdi: 'update-نوێکردنەوە',
      video: 'DuylBM10n_8',
      wana: "38",
      content: ""),
  Sharb(
      name: "بەزمانی کوردی",
      total: 'search-گەڕان',
      publisher: 'ferbun u zanst',
      image: 'images/c#.png',
      kurdi: 'search-گەڕان',
      video: 'DY5rBiFAJs4',
      wana: "39",
      content: ""),
  Sharb(
      name: "بەزمانی کوردی",
      total: 'Moving the image-جوڵاندنی وێنە',
      publisher: 'ferbun u zanst',
      image: 'images/c#.png',
      kurdi: 'Moving the image-جوڵاندنی وێنە',
      video: 'mIKvZIWfEtM',
      wana: "40",
      content: ""),
  Sharb(
      name: "بەزمانی کوردی",
      total: 'Using the keyboard-بەکارهینانی کیبۆرد',
      publisher: 'ferbun u zanst',
      image: 'images/c#.png',
      kurdi: 'Using the keyboard-بەکارهینانی کیبۆرد',
      video: 'M7BEguOU2Zk',
      wana: "41",
      content: ""),
  Sharb(
      name: "بەزمانی کوردی",
      total:
          'Mathematical operations by keyboard-کرداری بیرکاری بە ڕێگای کیبۆرد',
      publisher: 'ferbun u zanst',
      image: 'images/c#.png',
      kurdi:
          'Mathematical operations by keyboard-کرداری بیرکاری بە ڕێگای کیبۆرد',
      video: 'YPJM99plSlc',
      wana: "42",
      content: ""),
  Sharb(
      name: "بەزمانی کوردی",
      total:
          'Mathematical operations by keyboard 2 - 2 کرداری بیرکاری بە ڕێگای کیبۆرد',
      publisher: 'ferbun u zanst',
      image: 'images/c#.png',
      kurdi:
          'Mathematical operations by keyboard 2 - 2 کرداری بیرکاری بە ڕێگای کیبۆرد',
      video: 'YPJM99plSlc',
      wana: "43",
      content: ""),
  Sharb(
      name: "بەزمانی کوردی",
      total: 'View an image by keyboard-وێنەیەک بینین لەلایەن کیبۆردوە',
      publisher: 'ferbun u zanst',
      image: 'images/c#.png',
      kurdi: 'View an image by keyboard-وێنەیەک بینین لەلایەن کیبۆردوە',
      video: '5INMIGee9aY',
      wana: "44",
      content: ""),
  Sharb(
      name: "بەزمانی کوردی",
      total: 'Image storage-خەزنکردنی  وێنە',
      publisher: 'ferbun u zanst',
      image: 'images/c#.png',
      kurdi: 'Image storage-خەزنکردنی  وێنە',
      video: 'iDr4kOXAsAk',
      wana: "45",
      content: ""),
  Sharb(
      name: "بەزمانی کوردی",
      total:
          'Enter prices from the database or keyboard-داخیل کردنی نرخ لە دتابەیسەوە لەلەیان کیبۆرد',
      publisher: 'ferbun u zanst',
      image: 'images/c#.png',
      kurdi:
          'Enter prices from the database or keyboard-داخیل کردنی نرخ لە دتابەیسەوە لەلەیان کیبۆرد',
      video: 'bZo18jtVAD4',
      wana: "46",
      content: ""),
  Sharb(
      name: "بەزمانی کوردی",
      total:
          'Enter prices from the database or keyboard-داخیل کردنی نرخ لە دتابەیسەوە لەلەیان کیبۆرد',
      publisher: 'ferbun u zanst',
      image: 'images/c#.png',
      kurdi:
          'Enter prices from the database or keyboard-داخیل کردنی نرخ لە دتابەیسەوە لەلەیان کیبۆرد',
      video: 'bZo18jtVAD4',
      wana: "47",
      content: ""),
  Sharb(
      name: "بەزمانی کوردی",
      total: 'print-چاپکردن',
      publisher: 'ferbun u zanst',
      image: 'images/c#.png',
      kurdi: 'print-چاپکردن',
      video: '3-GgevnCiYA',
      wana: "48",
      content: ""),
  Sharb(
      name: "بەزمانی کوردی",
      total: 'print panel-پانێڵی چاپکردن',
      publisher: 'ferbun u zanst',
      image: 'images/c#.png',
      kurdi: 'print panel-پانێڵی چاپکردن',
      video: '8BWmDVLP6So',
      wana: "49",
      content: ""),
  Sharb(
      name: "بەزمانی کوردی",
      total: 'picture check box print-بۆکسی هەڵبژاردنی وێنە چاپ بکە',
      publisher: 'ferbun u zanst',
      image: 'images/c#.png',
      kurdi: 'picture check box print-بۆکسی هەڵبژاردنی وێنە چاپ بکە',
      video: 'KTcr6loBPug',
      wana: "50",
      content: ""),
  Sharb(
      name: "بەزمانی کوردی",
      total: 'print Gredviwe-دیمەنی تۆڕی چاپکردن',
      publisher: 'ferbun u zanst',
      image: 'images/c#.png',
      kurdi: 'print Gredviwe-دیمەنی تۆڕی چاپکردن',
      video: 'nMtXT2uyNcQ',
      wana: "51",
      content: ""),
  Sharb(
      name: "بەزمانی کوردی",
      total:
          'Pricing from Form 1 to Form 2-نرخ دانان لەفۆرم یەکەم بۆ فۆرمی دووەم',
      publisher: 'ferbun u zanst',
      image: 'images/c#.png',
      kurdi:
          'Pricing from Form 1 to Form 2-نرخ دانان لەفۆرم یەکەم بۆ فۆرمی دووەم',
      video: '8rJOPWogfKA',
      wana: "52",
      content: ""),
  Sharb(
      name: "بەزمانی کوردی",
      total:
          'Show us how to price DataGridView in textbox-چۆن نرخی داتاگریدڤیو لە تیکست بۆکس نیشانمان بدە',
      publisher: 'ferbun u zanst',
      image: 'images/c#.png',
      kurdi:
          'Show us how to price DataGridView in textbox-چۆن نرخی داتاگریدڤیو لە تیکست بۆکس نیشانمان بدە',
      video: 'zsJjGlbpDkA',
      wana: "53",
      content: ""),
  Sharb(
      name: "بەزمانی کوردی",
      total:
          'How to transfer a DataGridView value to another form-چۆن نرخی داتاگریدڤیو بگوازینەوە بۆ فۆرمی تر',
      publisher: 'ferbun u zanst',
      image: 'images/c#.png',
      kurdi:
          'How to transfer a DataGridView value to another form-چۆن نرخی داتاگریدڤیو بگوازینەوە بۆ فۆرمی تر',
      video: 'SndJoINh5CE',
      wana: "54",
      content: ""),
  Sharb(
      name: "بەزمانی کوردی",
      total: 'Analysis on the project-شیکردنەوە لەسەر پڕۆجیکت',
      publisher: 'ferbun u zanst',
      image: 'images/c#.png',
      kurdi: 'Analysis on the project-شیکردنەوە لەسەر پڕۆجیکت',
      video: 'K1_oQXzpu4E',
      wana: "55",
      content: ""),
  Sharb(
      name: "بەزمانی کوردی",
      total: 'Question mark?-نیشانی پرسیار',
      publisher: 'ferbun u zanst',
      image: 'images/c#.png',
      kurdi: 'Question mark?-نیشانی پرسیار',
      video: 'jbfV72xUvko',
      wana: "56",
      content: ""),
  Sharb(
      name: "بەزمانی کوردی",
      total: 'Question mark for GridView-نیشانی پرسیار بۆ گریدڤیو',
      publisher: 'ferbun u zanst',
      image: 'images/c#.png',
      kurdi: 'Question mark for GridView-نیشانی پرسیار بۆ گریدڤیو',
      video: 'oVeb-0ZPDQk',
      wana: "57",
      content: ""),
  Sharb(
      name: "بەزمانی کوردی",
      total: 'Question mark 2-2نیشانی پرسیار',
      publisher: 'ferbun u zanst',
      image: 'images/c#.png',
      kurdi: 'Question mark 2-2نیشانی پرسیار',
      video: 'lnkEZlwWOiI',
      wana: "58",
      content: ""),
  Sharb(
      name: "بەزمانی کوردی",
      total: 'Collection Value in TextBox-بەهای کۆکردنەوە لە سندوقی دەقدا',
      publisher: 'ferbun u zanst',
      image: 'images/c#.png',
      kurdi: 'Collection Value in TextBox-بەهای کۆکردنەوە لە سندوقی دەقدا',
      video: 'WZZmZrB8EAw',
      wana: "59",
      content: ""),
  Sharb(
      name: "بەزمانی کوردی",
      total: 'The price of taxes-نرخی باج',
      publisher: 'ferbun u zanst',
      image: 'images/c#.png',
      kurdi: 'The price of taxes-نرخی باج',
      video: 'nqqDuMcZgEI',
      wana: "60",
      content: ""),
  Sharb(
      name: "بەزمانی کوردی",
      total: 'Salary-مووچە',
      publisher: 'ferbun u zanst',
      image: 'images/c#.png',
      kurdi: 'Salary-مووچە',
      video: '3d2Zfb-MWTc',
      wana: "61",
      content: ""),
  Sharb(
      name: "بەزمانی کوردی",
      total:
          ' DatagridView Sum Column step by step-ستوونی کۆی داتاگریدڤیو هەنگاو بە هەنگاو',
      publisher: 'ferbun u zanst',
      image: 'images/c#.png',
      kurdi:
          ' DatagridView Sum Column step by step-ستوونی کۆی داتاگریدڤیو هەنگاو بە هەنگاو',
      video: 'YDShSNO2qjo',
      wana: "62",
      content: ""),
  Sharb(
      name: "بەزمانی کوردی",
      total: 'Currency-دراو',
      publisher: 'ferbun u zanst',
      image: 'images/c#.png',
      kurdi: 'Currency-دراو',
      video: 'CkQpPUIVSik',
      wana: "63",
      content: ""),
  Sharb(
      name: "بەزمانی کوردی",
      total:
          'DatagridView Sum Row and Column step by-تۆڕی داتا بینینی کۆی ڕیز و ستوون هەنگاو بە هەنگاو',
      publisher: 'ferbun u zanst',
      image: 'images/c#.png',
      kurdi:
          'DatagridView Sum Row and Column step by-تۆڕی داتا بینینی کۆی ڕیز و ستوون هەنگاو بە هەنگاو',
      video: 'L6ckNCYis-c',
      wana: "64",
      content: ""),
  Sharb(
      name: "بەزمانی کوردی",
      total:
          'Sum Column in DataGridview Automatically-ستوونی کۆکردنەوە لە دیمەنی تۆڕی داتا بە شێوەیەکی ئۆتۆماتیکی',
      publisher: 'ferbun u zanst',
      image: 'images/c#.png',
      kurdi:
          'Sum Column in DataGridview Automatically-ستوونی کۆکردنەوە لە دیمەنی تۆڕی داتا بە شێوەیەکی ئۆتۆماتیکی',
      video: 'bFcvnaZxv6Y',
      wana: "65",
      content: ""),
  Sharb(
      name: "بەزمانی کوردی",
      total: 'Sum Column in Keyboard Step By Step-',
      publisher: 'ferbun u zanst',
      image: 'images/c#.png',
      kurdi:
          'Sum Column in Keyboard Step By Step-ستوونی کۆکردنەوە لە کیبۆرد هەنگاو بە هەنگاو',
      video: 'WPukERG9O8Q',
      wana: "66",
      content: ""),
  Sharb(
      name: "بەزمانی کوردی",
      total:
          ' Library Management System Project in-پڕۆژەی سیستەمی بەڕێوەبردنی کتێبخانە لە...',
      publisher: 'ferbun u zanst',
      image: 'images/c#.png',
      kurdi:
          ' Library Management System Project in-پڕۆژەی سیستەمی بەڕێوەبردنی کتێبخانە لە...',
      video: '6SwtVw3np0o',
      wana: "67",
      content: ""),
  Sharb(
      name: "بەزمانی کوردی",
      total:
          ' Make Recept Table Library Management-بەڕێوەبردنی کتێبخانەی مێزی وەرگرتن دروست بکە',
      publisher: 'ferbun u zanst',
      image: 'images/c#.png',
      kurdi: '6tsgPRGmhIA',
      video:
          ' Make Recept Table Library Management-بەڕێوەبردنی کتێبخانەی مێزی وەرگرتن دروست بکە',
      wana: "68",
      content: ""),
  Sharb(
      name: "بەزمانی کوردی",
      total:
          'Make Recept Table Library Management-بەڕێوەبردنی کتێبخانەی مێزی وەرگرتن دروست بکە',
      publisher: 'ferbun u zanst',
      image: 'images/c#.png',
      kurdi:
          'Make Recept Table Library Management-بەڕێوەبردنی کتێبخانەی مێزی وەرگرتن دروست بکە',
      video: '6tsgPRGmhIA',
      wana: "69",
      content: ""),
  Sharb(
      name: "بەزمانی کوردی",
      total:
          'View Data to DataGridview in Library-بینینی داتا بۆ داتا گریدڤیو لە کتێبخانە',
      publisher: 'ferbun u zanst',
      image: 'images/c#.png',
      kurdi:
          'View Data to DataGridview in Library-بینینی داتا بۆ داتا گریدڤیو لە کتێبخانە',
      video: 'rgTQPkFlqho',
      wana: "70",
      content: ""),
  Sharb(
      name: "بەزمانی کوردی",
      total:
          ' Insert and Update to DataGridview in Library Management System-جێگیرکردن و نوێکردنەوە بۆ دیمەنی تۆڕی داتا لە سیستەمی بەڕێوەبردنی کتێبخانە',
      publisher: 'ferbun u zanst',
      image: 'images/c#.png',
      kurdi:
          ' Insert and Update to DataGridview in Library Management System-جێگیرکردن و نوێکردنەوە بۆ دیمەنی تۆڕی داتا لە سیستەمی بەڕێوەبردنی کتێبخانە',
      video: 'GmHVcH_h_2c',
      wana: "71",
      content: ""),
  Sharb(
      name: "بەزمانی کوردی",
      total:
          'Search and Delete to DataGridview in Library Management-گەڕان و سڕینەوە بۆ دیمەنی تۆڕی داتا لە بەڕێوەبردنی کتێبخانە',
      publisher: 'ferbun u zanst',
      image: 'images/c#.png',
      kurdi:
          'Search and Delete to DataGridview in Library Management-گەڕان و سڕینەوە بۆ دیمەنی تۆڕی داتا لە بەڕێوەبردنی کتێبخانە',
      video: 'kPbvfhugdXI',
      wana: "72",
      content: ""),
  Sharb(
      name: "بەزمانی کوردی",
      total:
          'Sum and Average DataGridview Column in Library Management System-کۆ و تێکڕای ستوونی داتاگریتڤیو لە سیستەمی بەڕێوەبردنی کتێبخانەدا',
      publisher: 'ferbun u zanst',
      image: 'images/c#.png',
      kurdi:
          'Sum and Average DataGridview Column in Library Management System-کۆ و تێکڕای ستوونی داتاگریتڤیو لە سیستەمی بەڕێوەبردنی کتێبخانەدا',
      video: 'XTV5xnzyBAo',
      wana: "73",
      content: ""),
  Sharb(
      name: "بەزمانی کوردی",
      total: ' How To Load Data From SQL Server Database && Set Into TextBox',
      publisher: 'ferbun u zanst',
      image: 'images/c#.png',
      kurdi: ' How To Load Data From SQL Server Database && Set Into TextBox',
      video: 'GUBV3hCd1Jw',
      wana: "74",
      content: ""),
  Sharb(
      name: "بەزمانی کوردی",
      total:
          'How To ADD MenuStrip Control-چۆنێتی زیادکردنی کۆنترۆڵی شریتی مێنۆ',
      publisher: 'ferbun u zanst',
      image: 'images/c#.png',
      kurdi:
          'How To ADD MenuStrip Control-چۆنێتی زیادکردنی کۆنترۆڵی شریتی مێنۆ',
      video: 'Lb3SExCo4lU',
      wana: "75",
      content: ""),
  Sharb(
      name: "بەزمانی کوردی",
      total:
          'SQL server Primary key Auto Increment Visual Studio && C# Windows Form Application',
      publisher: 'ferbun u zanst',
      image: 'images/c#.png',
      kurdi:
          'SQL server Primary key Auto Increment Visual Studio && C# Windows Form Application',
      video: 'CPQu0tQtM-E',
      wana: "76",
      content: ""),
  Sharb(
      name: "بەزمانی کوردی",
      total: ' Convert Text To Voice Speech-گۆڕینی دەق بۆ قسەکردنی دەنگی',
      publisher: 'ferbun u zanst',
      image: 'images/c#.png',
      kurdi: ' Convert Text To Voice Speech-گۆڕینی دەق بۆ قسەکردنی دەنگی',
      video: 'EJ-gz0jkypQ',
      wana: "77",
      content: ""),
  Sharb(
      name: "بەزمانی کوردی",
      total: 'ImageList-ImageList',
      publisher: 'ferbun u zanst',
      image: 'images/c#.png',
      kurdi: 'ImageList-لیستی وێنەکان',
      video: 'AxLOlfXIF2I',
      wana: "78",
      content: ""),
  Sharb(
      name: "بەزمانی کوردی",
      total: 'Robort Animation-ئەنیمەیشنی ڕۆبۆت',
      publisher: 'ferbun u zanst',
      image: 'images/c#.png',
      kurdi: 'Robort Animation-ئەنیمەیشنی ڕۆبۆت',
      video: 'RxLsYFRXFiw',
      wana: "79",
      content: ""),
  Sharb(
      name: "بەزمانی کوردی",
      total: 'Foot Shop-دوکانی پێ',
      publisher: 'ferbun u zanst',
      image: 'images/c#.png',
      kurdi: 'Foot Shop-دوکانی پێ',
      video: 'YP49A2XfU_8',
      wana: "80",
      content: ""),
  Sharb(
      name: "بەزمانی کوردی",
      total: 'FootBall Game-یاری تۆپی پێ',
      publisher: 'ferbun u zanst',
      image: 'images/c#.png',
      kurdi: 'FootBall Game-یاری تۆپی پێ',
      video: 'bIAtCcahd40',
      wana: "81",
      content: ""),
  Sharb(
      name: "بەزمانی کوردی",
      total: 'Motorcycle Game-یاری ماتۆڕسکیل',
      publisher: 'ferbun u zanst',
      image: 'images/c#.png',
      kurdi: 'Motorcycle Game-یاری ماتۆڕسکیل',
      video: 'n3xyVWXgbvs',
      wana: "82",
      content: ""),
  Sharb(
      name: "بەزمانی کوردی",
      total: ' Car Game-یاری ئۆتۆمبێل',
      publisher: 'ferbun u zanst',
      image: 'images/c#.png',
      kurdi: ' Car Game-یاری ئۆتۆمبێل',
      video: 'HHSqXcqk_Xc',
      wana: "83",
      content: ""),
  Sharb(
      name: "بەزمانی کوردی",
      total: 'Traffic Light-ترافیک لایت',
      publisher: 'ferbun u zanst',
      image: 'images/c#.png',
      kurdi: 'Traffic Light-ترافیک لایت',
      video: 'SzTmIXTnaxg',
      wana: "84",
      content: ""),
  Sharb(
      name: "بەزمانی کوردی",
      total: ' Project Full Tutorial-فێرکاری تەواوی پڕۆژە',
      publisher: 'ferbun u zanst',
      image: 'images/c#.png',
      kurdi: ' Project Full Tutorial-فێرکاری تەواوی پڕۆژە',
      video: 'ISh-gFFNAe8',
      wana: "85",
      content: ""),
  Sharb(
      name: "بەزمانی کوردی",
      total: 'Currency Converter-گۆرینەوەی دراو',
      publisher: 'ferbun u zanst',
      image: 'images/c#.png',
      kurdi: 'Currency Converter-گۆرینەوەی دراو',
      video: '6wWssDOd_Gw',
      wana: "86",
      content: ""),
  Sharb(
      name: "بەزمانی کوردی",
      total: 'Integer-ژمارە تەواو',
      publisher: 'ferbun u zanst',
      image: 'images/c#.png',
      kurdi: 'Integer-ژمارە تەواو',
      video: 'YsYBzij68Sw',
      wana: "87",
      content: ""),
  Sharb(
      name: "بەزمانی کوردی",
      total: ' Double-دوو هێندە',
      publisher: 'ferbun u zanst',
      image: 'images/c#.png',
      kurdi: ' Double-دوو هێندە',
      video: 'vjV6A0SA8MM',
      wana: "88",
      content: ""),
  Sharb(
      name: "بەزمانی کوردی",
      total: ' Calculator-بژمێر',
      publisher: 'ferbun u zanst',
      image: 'images/c#.png',
      kurdi: ' Calculator-بژمێر',
      video: '8ZqBCZZD0pk',
      wana: "89",
      content: ""),
  Sharb(
      name: "بەزمانی کوردی",
      total: 'Boolean-راست و هەڵە',
      publisher: 'ferbun u zanst',
      image: 'images/c#.png',
      kurdi: 'Boolean-راست و هەڵە',
      video: 'bAAqPAraHtE',
      wana: "90",
      content: ""),
  Sharb(
      name: "بەزمانی کوردی",
      total: 'Web Browser',
      publisher: 'ferbun u zanst',
      image: 'images/c#.png',
      kurdi: 'Web Browser',
      video: '69HyPU0o6kY',
      wana: "91",
      content: ""),
  Sharb(
      name: "بەزمانی کوردی",
      total: ' RichTextBox-سندوقی دەوڵەمەند',
      publisher: 'ferbun u zanst',
      image: 'images/c#.png',
      kurdi: ' RichTextBox-سندوقی دەوڵەمەند',
      video: 'P1Bpy8EbKZ0',
      wana: "92",
      content: ""),
  Sharb(
      name: "بەزمانی کوردی",
      total:
          ' Hide Rows and Column from DataGridView-شاردنەوەی ڕیز و ستوونی لەداتاگریتڤیو ',
      publisher: 'ferbun u zanst',
      image: 'images/c#.png',
      kurdi:
          ' Hide Rows and Column from DataGridView- شاردنەوەی ڕیز و ستوونی لەداتاگریتڤیو  ',
      video: 'EqALom-FXN8',
      wana: "93",
      content: ""),
  Sharb(
      name: "بەزمانی کوردی",
      total: 'IF Statement-ئەگەر بەیاننامە',
      publisher: 'ferbun u zanst',
      image: 'images/c#.png',
      kurdi: 'IF Statement-ئەگەر بەیاننامە',
      video: 'C1gp3Q1E6vI',
      wana: "94",
      content: ""),
  Sharb(
      name: "بەزمانی کوردی",
      total: 'FOR LOOPS-بۆ لوپەکان',
      publisher: 'ferbun u zanst',
      image: 'images/c#.png',
      kurdi: 'FOR LOOPS-بۆ لوپەکان',
      video: 'TV4FrQKr7_Y',
      wana: "95",
      content: ""),
  Sharb(
      name: "بەزمانی کوردی",
      total: ' WHILE LOOPS-لە کاتێکدا لوپەکان',
      publisher: 'ferbun u zanst',
      image: 'images/c#.png',
      kurdi: ' WHILE LOOPS-لە کاتێکدا لوپەکان',
      video: 'JUrleXf1H1c',
      wana: "96",
      content: ""),
  Sharb(
      name: "بەزمانی کوردی",
      total: 'do_while-بیکە لە کاتێکدا',
      publisher: 'ferbun u zanst',
      image: 'images/c#.png',
      kurdi: 'do_while-بیکە لە کاتێکدا',
      video: 'SJHU1SisUnE',
      wana: "97",
      content: ""),
];



/*
import 'package:flutter/material.dart';

class Flatr {
  String name, total, image, publisher, wana, zhmara;
  Flatr(this.name, this.total, this.wana, this.zhmara, this.publisher,
      this.image);
  static map(Widget Function(dynamic all) parama0) {}
}

List<Flatr> flatr = [
  Flatr("پێشەکی کۆرسی فلاوتەربی", "بەزمانی کوردی", 'وانەی', 'یەکەم
      'Taco Group', 'images/flutter.png'),
  Flatr("پێشەکی کۆرسی فلاوتەربی", "بەزمانی کوردی", 'وانەی', 'یەکەم',
      'Taco Group', 'images/flutter.png'),
  Flatr("پێشەکی کۆرسی فلاوتەربی", "بەزمانی کوردی", 'وانەی', 'یەکەم',
      'Taco Group', 'images/flutter.png'),
  Flatr("پێشەکی کۆرسی فلاوتەربی", "بەزمانی کوردی", 'وانەی', 'یەکەم',
      'Taco Group', 'images/flutter.png'),
];
'*/